### PR TITLE
Fix dolt version error when repo state is missing

### LINKED ISSUE #4154: `dolt version` errors when run from directory containing `DOLT_ROOT_PATH`
```bash
% dolt version
dolt version 0.40.27
The current directories repository state is invalid
open /home/user/.dolt/repo_state.json: no such file or directory

% ls -a 
.dolt 

% ls .dolt
config_global.json  creds
```

### PR DESCRIPTION
**Pull request by tanyongzhi**
Fixes #4154 

Not sure if tests are required for this?

### CODE REVIEW

**Comment by fulghum** [comment]
Hey @tanyongzhi, thanks for sending us another awesome PR! 

I tagged @druvv to take a look at the review today for you, since he has been working in this code lately. A test would definitely be helpful, and Dhruv can probably give a good suggestion on where to add one. 

@druvv – do you have a suggestion on the right place for a BATS test Yong could add? It looks like `no-repo.bats` has some tests for `dolt version` that are worth looking over and `init.bats` has a couple of references, too.

**Comment by druvv** [comment]
Hi @tanyongzhi,

Thank you for the fix! I would recommend making a bats test under `//integration-tests/bats/no-repo.bats` to test this behavior. We have an existing test for `dolt version` there. An idea on how to test this is to make an empty `.dolt` folder and ensure that status code zero is returned.

**Comment by timsehn** [comment]
Checking to see if this also fixes this:

https://github.com/dolthub/dolt/issues/2898

**Comment by timsehn** [comment]
Denied!
```
 ✗ no-repo: dolt version does not need write permissions
   (in test file integration-tests/bats/no-repo.bats, line 114)
     `[ "$status" -eq 0 ]' failed
   Successfully initialized dolt data repository.
   rm: /var/folders/t7/90tpn01n59j1mqt6xnvyv9m80000gn/T/dolt-repo-60815/no-dolt-dir-60815: Permission denied
   rm: /var/folders/t7/90tpn01n59j1mqt6xnvyv9m80000gn/T/dolt-repo-60815: Permission denied
```

Thanks for the contribution. @fulghum we should get this merged in!

**Comment by fulghum** [comment]
Thanks for yet another great contribution @tanyongzhi! 🎉  We really appreciate you taking the time to send us this! 🙏

**Pull request merged**
