### PR TITLE
test cockroachdb/swiss

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>ea3db4b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>ea3db4b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 99.33             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | dbf657ba679f853e77f78efd1cf7cf3b918a56ec | 22.41 | tpcc-scale-factor-1 | dolt        | ea3db4b3ac7bbd902ce7bdec702fc33288c9b095 | 22.19 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.07                | 2.91              | 0         |
| groupby_scan         | 17.63               | 17.32             | 0         |
| index_join           | 5.18                | 5.09              | 0         |
| index_join_scan      | 2.22                | 2.18              | 0         |
| index_scan           | 53.85               | 54.83             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.43                | 8.43              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.95              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 137.35              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.91              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.12               | 16.12             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.84              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Pull request closed without merging**
