### PR TITLE
[no-release-notes] bump for more insert perf

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 82.96            | 82.96          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 0ca0493dcb6f12a622b3d890e8f4c980ed0e2562 | 25.67 | tpcc-scale-factor-1 | dolt        | 51a834565041103bcdfec2c5e1cec92710930897 | 25.9 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.91              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.49                | 0.5               | 0         |
| oltp_read_only       | 7.98                | 8.13              | 0         |
| select_random_points | 0.78                | 0.8               | 0         |
| select_random_ranges | 0.95                | 0.97              | 0         |
| table_scan           | 53.85               | 54.83             | 0         |
| types_table_scan     | 134.9               | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 14.46               | 14.73             | 0         |
| oltp_update_index     | 3.13                | 3.13              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 6.43                | 6.55              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Pull request closed without merging**
