### PR TITLE
[no-release-notes] parser perf bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>1dc8d8f</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>1dc8d8f</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 64.47            | 59.99          | -6.95          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | cec1febbae9e9855548d3700a10a359b5d5ce763 | 40.66    | dolt           | 1dc8d8fef7c1293d1e08ae290ddfb9347e4cf4a5 | 40.88  | 0.54           |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.69         | 0.63       | -8.7           |
| groupby_scan         | 17.01        | 16.71      | -1.76          |
| index_join           | 2.35         | 2.3        | -2.13          |
| index_join_scan      | 1.89         | 1.89       | 0.0            |
| index_scan           | 55.82        | 55.82      | 0.0            |
| oltp_point_select    | 0.3          | 0.27       | -10.0          |
| oltp_read_only       | 5.77         | 5.47       | -5.2           |
| select_random_points | 0.65         | 0.61       | -6.15          |
| select_random_ranges | 0.7          | 0.63       | -10.0          |
| table_scan           | 56.84        | 56.84      | 0.0            |
| types_table_scan     | 147.61       | 147.61     | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 5.99         | 5.88       | -1.84          |
| oltp_insert           | 2.97         | 2.91       | -2.02          |
| oltp_read_write       | 11.87        | 11.24      | -5.31          |
| oltp_update_index     | 3.02         | 2.97       | -1.66          |
| oltp_update_non_index | 2.97         | 2.91       | -2.02          |
| oltp_write_only       | 6.09         | 5.99       | -1.64          |
| types_delete_insert   | 6.43         | 6.32       | -1.71          |

**Pull request merged**
