### PR TITLE
[no-release-notes] test update/delete perf bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>429a034</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>429a034</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 87.56               | 84.47             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 902d06cda55e031ffc96503ad48371f8683e86d1 | 24.73 | tpcc-scale-factor-1 | dolt        | 429a03470199ab731ce78d240a7d5b6ede5b828e | 25.12 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.28                | 5.37              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.52                | 0.52              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 55.82               | 56.84             | 0         |
| types_table_scan     | 139.85              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.32                | 6.32              | 0         |
| oltp_insert           | 3.07                | 3.07              | 0         |
| oltp_read_write       | 15.27               | 15.27             | 0         |
| oltp_update_index     | 3.25                | 3.25              | 0         |
| oltp_update_non_index | 3.19                | 3.19              | 0         |
| oltp_write_only       | 6.91                | 6.79              | 0         |
| types_delete_insert   | 7.04                | 7.04              | 0         |

**Pull request closed without merging**
