### PR TITLE
[no-release-notes] add dolt ci init and destroy

### PR DESCRIPTION
**Pull request by coffeegoddd**
This PR adds hidden commands for creating and destroying Dolt CI tables, which will be used for continuous integration on DoltHub/DoltLab.

Currently, when the hidden dolt ci commands are run, they will create/destroy all dolt ci tables and create a new dolt commit. However, this commit does not produce a diff. 

These CI tables are currently alterable, so user's can change their contents and schema. Ideally, these would only be alterable/writeable by dolt itself, but we have no such interface for that.

Currently, the method `CreateDoltCITables` uses the approach of creating the tables against the root value. I didn't think to pass the `queryist.Query` method down until I created `DestroyDoltCITables`, so it's possible that's the preferred approach?

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0157405</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0157405</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by fulghum — APPROVED** [review]
Looks good. Nothing major, but some suggestions for additional tests as well as a few things I think would help tidy up the changes or make it easier for future code readers. 

I didn't think much about the specific table structure/design – I think I remember that being reviewed in a doc a while back. Let me know if you are looking for feedback on that, too, and I'm happy to spend a little time thinking about it.

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>f13749a</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>f13749a</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c07ba36</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c07ba36</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
