### PR TITLE
[no-release-notes] insert perf bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a06876e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a06876e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 92.42               | 87.56             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | fa83e8dfe0123137bc30d9abca17a9d0eaae0cf8 | 23.45 | tpcc-scale-factor-1 | dolt        | a06876e090a1497d874a4609085d2c4d203ca16d | 24.4 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.18                | 5.28              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.52                | 0.51              | 0         |
| oltp_read_only       | 8.43                | 8.28              | 0         |
| select_random_points | 0.83                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 137.35              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.67                | 6.32              | 0         |
| oltp_insert           | 3.25                | 3.07              | 0         |
| oltp_read_write       | 15.83               | 15.27             | 0         |
| oltp_update_index     | 3.43                | 3.25              | 0         |
| oltp_update_non_index | 3.36                | 3.19              | 0         |
| oltp_write_only       | 7.43                | 6.91              | 0         |
| types_delete_insert   | 7.43                | 7.04              | 0         |

**Pull request closed without merging**
