### PR TITLE
test swapping swiss

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>8e76be0</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>8e76be0</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 84.47               | 94.1              | 0         |


|      test_name      | server_name |              server_version              | tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 6ac3aaf83ce6b2ff007f02439afa51d6dd6bfd06 | 0.48 | tpcc-scale-factor-1 | dolt        | 8e76be0e35742e06fe175d6772e260e86870bc7d | 14.35 | -1        |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.63             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.26                | 2.26              | 0         |
| index_scan           | 55.82               | 54.83             | 0         |
| oltp_point_select    | 0.54                | 0.54              | 0         |
| oltp_read_only       | 8.58                | 8.58              | 0         |
| select_random_points | 0.84                | 0.84              | 0         |
| select_random_ranges | 1.01                | 1.01              | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 161.51              | 161.51            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.91              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.41               | 16.41             | 0         |
| oltp_update_index     | 3.55                | 3.55              | 0         |
| oltp_update_non_index | 3.49                | 3.49              | 0         |
| oltp_write_only       | 7.98                | 7.98              | 0         |
| types_delete_insert   | 7.7                 | 7.7               | 0         |

**Pull request closed without merging**
