### PR TITLE
fix: avoid empty commit body issue

### PR DESCRIPTION
**Pull request by chenrui333**
image

cc @oscarbatori

### CODE REVIEW

**Comment by chenrui333** [comment]
I am not going to merge the two open PRs until this one being merged. 

cc @oscarbatori @VinaiRachakonda

**Comment by chenrui333** [comment]
The current dolt PR process does cause unnecessary maintenance overhead.

**Comment by VinaiRachakonda** [comment]
Understood! @oscarbatori and I will sync up and handle this. Sorry for the inconvenience.

**Comment by oscarbatori** [comment]
> I am not going to merge the two open PRs until this one being merged.
> 
> cc @oscarbatori @VinaiRachakonda

@chenrui333 - that's fair, I apologize that it took us a while to get to this. We will have it resolved presently. The PR is currently breaking a subsequent job, but I am not sure why.

In the mean time, can we merge [this](https://github.com/Homebrew/homebrew-core/pull/68851)? It's an important bug fix, and we will merge above in short order so this won't happen again.

**Comment by oscarbatori** [comment]
Merging this despite CI failure. Cause is that forks don't have access to our Discord notification webhook.

**Pull request merged**
