### PR TITLE
Improve Error message when merge fails because of different primary keys

### PR DESCRIPTION
**Pull request by katiemcculloch**
This is much more descriptive IMO, but lmk if you have suggestions for how to word it.

### CODE REVIEW

**Comment by timsehn** [comment]
Can I get a more descriptive PR title since it goes in the release notes?

Something like: "Improve Error message when merge fails because of different primary keys"

**Comment by timsehn** [comment]
Merge Failed. Tables with different primary keys cannot be merged.

?

**Comment by katiemcculloch** [comment]
> Merge Failed. Tables with different primary keys cannot be merged.
> 
> ?

that's mo betta, thx

**Review by bheni — APPROVED** [review]
lgtm

**Pull request merged**
