### PR TITLE
fix sqllogictest harness to use float rounding

### PR DESCRIPTION
**Pull request by jycor**
When we generated the results for MySQL (specifically the float results), we used the golang `fmt.Sprintf('%.3f')` string, even for decimal types. Meanwhile, the doltharness was using `decimal.Round()`. There's evidently a difference in the way these two rounding operations work, so we had some failures due to rounding errors.

This PR makes it so decimals are rounded the same way floats are, so that results are consistent.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.998653 to 99.998602</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4e38973</TD>
<TD>not ok</TD>
<TD>83</TD>
</TR>
<TR><TD>4e38973</TD>
<TD>ok</TD>
<TD>5937374</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4e38973</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.998602</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.998653 to 99.998602</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a1ee787</TD>
<TD>not ok</TD>
<TD>83</TD>
</TR>
<TR><TD>a1ee787</TD>
<TD>ok</TD>
<TD>5937374</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a1ee787</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.998602</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.998653 to 99.998771</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0e933ab</TD>
<TD>not ok</TD>
<TD>73</TD>
</TR>
<TR><TD>0e933ab</TD>
<TD>ok</TD>
<TD>5937384</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0e933ab</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.998771</TD>
</TR>
</table>

**Review by max-hoffman — APPROVED** [review]
lgtm but a test for a query that fails without this would be nice

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.998669 to 99.998787</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4847a98</TD>
<TD>not ok</TD>
<TD>72</TD>
</TR>
<TR><TD>4847a98</TD>
<TD>ok</TD>
<TD>5937385</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4847a98</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.998787</TD>
</TR>
</table>

**Pull request merged**
