### PR TITLE
store/datas: fix dropped errors

### PR DESCRIPTION
**Pull request by alrs**
This fixes three dropped `err` variables in the `store/datas` package.

### CODE REVIEW

**Comment by alrs** [comment]
Are the two CI failures a flake, or legitimate?

**Comment by timsehn** [comment]
I'll re-run. Not sure but definitely looks unrelated to your change.

**Comment by timsehn** [comment]
This looks deterministic but it's unclear this was you. Consulting the team.

**Comment by timsehn** [comment]
Testing locally.
```
$ git checkout --track alrs/store-datas-errs 
branch 'store-datas-errs' set up to track 'alrs/store-datas-errs'.
Switched to a new branch 'store-datas-errs'
$ git pull && cd go/cmd/dolt && go install . && cd -
Already up to date.
~/dolthub/git/dolt
$ bats integration-tests/bats 
1pk5col-ints.bats
 ✓ 1pk5col-ints: empty table
 ✓ 1pk5col-ints: create a table, dolt add, dolt reset, and dolt commit
 ✓ 1pk5col-ints: add a row to a created table using dolt table put-row
 ✓ 1pk5col-ints: dolt sql all manner of inserts
 ✓ 1pk5col-ints: dolt sql insert same column twice
 ✓ 1pk5col-ints: dolt sql insert no columns specified
...
```

**Comment by timsehn** [comment]
Passed on. my mac:
```
...
 ✓ verify-constraints: CLI missing --all and --output-only, no named tables
 ✓ verify-constraints: CLI missing --all and --output-only, named tables
 ✓ verify-constraints: CLI --all
 ✓ verify-constraints: CLI --output-only
 ✓ verify-constraints: CLI --all and --output-only
window.bats
 ✓ window: no diff table window buffer sharing

2397 tests, 0 failures, 166 skipped
```

**Comment by timsehn** [comment]
Looks like a flake. Just needs the formatter.

**Comment by timsehn** [comment]
Merging. Thanks!

**Pull request merged**
