### PR TITLE
Update validation for dropping an `auto_increment` primary key column

### PR DESCRIPTION
**Pull request by fulghum**
Allows `auto_increment` primary key columns to be dropped, so long as there exists a secondary index that covers the `auto_increment` column. 

Depends on https://github.com/dolthub/go-mysql-server/pull/2316

Related to https://github.com/dolthub/dolt/issues/7456

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999124</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>fd4b048</TD>
<TD>not ok</TD>
<TD>52</TD>
</TR>
<TR><TD>fd4b048</TD>
<TD>ok</TD>
<TD>5937405</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>fd4b048</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999124</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999124</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0f95427</TD>
<TD>not ok</TD>
<TD>52</TD>
</TR>
<TR><TD>0f95427</TD>
<TD>ok</TD>
<TD>5937405</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0f95427</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999124</TD>
</TR>
</table>

**Review by zachmu — APPROVED** [review]
LGTM!

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999562</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>41604c3</TD>
<TD>not ok</TD>
<TD>26</TD>
</TR>
<TR><TD>41604c3</TD>
<TD>ok</TD>
<TD>5937431</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>41604c3</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999562</TD>
</TR>
</table>

**Pull request merged**
