### PR TITLE
[store] use the cache for child refs

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 108.68              | 112.67            | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 676c7e9f00ca7cdf07fd1e77fddb6ed20edb5990 | 22.53 | tpcc-scale-factor-1 | dolt        | a19d18b5d97d45d742b057a270347970d05b4cc6 | 8.32 | 1         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a19d18b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a19d18b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.02                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.63             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.26              | 0         |
| index_scan           | 63.32               | 63.32             | 0         |
| oltp_point_select    | 0.48                | 0.48              | 0         |
| oltp_read_only       | 8.13                | 8.13              | 0         |
| select_random_points | 0.78                | 0.78              | 0         |
| select_random_ranges | 0.94                | 0.94              | 0         |
| table_scan           | 63.32               | 63.32             | 0         |
| types_table_scan     | 176.73              | 173.58            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 7.04              | 0         |
| oltp_insert           | 3.43                | 3.49              | 0         |
| oltp_read_write       | 15.83               | 16.12             | 0         |
| oltp_update_index     | 3.55                | 3.62              | 0         |
| oltp_update_non_index | 3.49                | 3.55              | 0         |
| oltp_write_only       | 7.98                | 8.28              | 0         |
| types_delete_insert   | 7.7                 | 7.7               | 0         |

**Comment by max-hoffman** [comment]
bit surprising, but seems like the CPU indirection is more expensive than writing a bunch of extra refs on the CI hardware

**Pull request closed without merging**
