### PR TITLE
go/store/nbs: tableReader, *NomsBlockStore: Use errgroup.SetLimit to enforce limit on io parallelism across the GetMany call, instead of just at the chunk source.

### PR DESCRIPTION
**Pull request by reltuk**

### CODE REVIEW

**Comment by reltuk** [comment]
#benchmark

**Review by andy-wm-arthur — APPROVED** [review]
LGTM!

**Comment by reltuk** [comment]
#benchmark

**Comment by reltuk** [comment]
See #5298 for another set of benchmarks. Merging for now.

**Pull request merged**
