### PR TITLE
Persist table comment from `create table`

### PR DESCRIPTION
**Pull request by fulghum**
We already parse table comments, but they were not persisted anywhere. This change adds support for persisting table comments so that they can be round-tripped between `create table` and `show create table`.

In addition to the follow ups in the GMS layer (mentioned in https://github.com/dolthub/go-mysql-server/pull/2307), there is one follow up in the dolt layer to update Dolt's merge logic to merge table comment changes. 

Depends on https://github.com/dolthub/go-mysql-server/pull/2307

Related to https://github.com/dolthub/dolt/issues/7416

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999074 to 99.994240</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7894356</TD>
<TD>not ok</TD>
<TD>342</TD>
</TR>
<TR><TD>7894356</TD>
<TD>ok</TD>
<TD>5937115</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7894356</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.99424</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999074 to 99.999074</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>95048e7</TD>
<TD>not ok</TD>
<TD>55</TD>
</TR>
<TR><TD>95048e7</TD>
<TD>ok</TD>
<TD>5937402</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>95048e7</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999074</TD>
</TR>
</table>

**Review by zachmu — APPROVED** [review]
LGTM!

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999074 to 99.999074</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>89355f4</TD>
<TD>not ok</TD>
<TD>55</TD>
</TR>
<TR><TD>89355f4</TD>
<TD>ok</TD>
<TD>5937402</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>89355f4</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999074</TD>
</TR>
</table>

**Pull request merged**
