### PR TITLE
[no-release-notes] Subtree counts as delta encoded varints 

### PR DESCRIPTION
**Pull request by andrew-wm-arthur**
Internal prolly nodes store subtree cardinalities for each child pointer. These are necessary to compute the total cardinality of a tree during tree mutation/chunking. These cardinalities are varint encoded to save space, as they are only needed on the write path. 

This pr changes the encoding format to store cardinality values as the delta of the minimum subtree cardinality for that node. This results in significant space savings for level 1 nodes where the difference between the greatest and least cardinality is typically less than 128, meaning that each value can be encoded in 1 byte.

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
Encoded size comparison for 3 encoding techniques
```
direct varint level_1 (mean_size:_258.043600) 
direct varint level_2 (mean_size:_436.127200) 
direct varint level_3 (mean_size:_600.000000) 
direct varint level_4 (mean_size:_750.000000)

min_delta_varint level_1 (mean_size:_151.000000)
min_delta_varint level_2 (mean_size:_299.727100)
min_delta_varint level_3 (mean_size:_460.095200)
min_delta_varint level_4 (mean_size:_630.774700)

signed_delta_varint level_1 (mean_size:_170.226000)
signed_delta_varint level_2 (mean_size:_330.397000)
signed_delta_varint level_3 (mean_size:_492.416300)
signed_delta_varint level_4 (mean_size:_654.063800)

for uniformly distributed data:
level_1: [100:200]
level_2: [15000:30000]
level_3: [2250000:4500000]
level_4: [337500000:675000000]
```

**Review by reltuk — APPROVED** [review]
LGTM!

**Comment by andrew-wm-arthur** [comment]
After further thought, encoding signed deltas is likely a more sensible default. Signed deltas have the best locality for in-place edits, which is advantageous if persistence layers do additional delta-encoding on chunks.

**Comment by andrew-wm-arthur** [comment]
Updated benchmarks after switching to Gaussian distributed test data:
```
goos: darwin
goarch: amd64
pkg: github.com/dolthub/dolt/go/store/prolly/message
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkVarint
BenchmarkVarint/signed_delta_varint
BenchmarkVarint/signed_delta_varint/level_1_subtree_counts
BenchmarkVarint/signed_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)
BenchmarkVarint/signed_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)-12         	 1617583	       640.6 ns/op
BenchmarkVarint/signed_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_184.165000)
BenchmarkVarint/signed_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_184.165000)-12     	 1247400	       901.3 ns/op
BenchmarkVarint/signed_delta_varint/level_2_subtree_counts
BenchmarkVarint/signed_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)
BenchmarkVarint/signed_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)-12     	 1584252	       675.1 ns/op
BenchmarkVarint/signed_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_345.370000)
BenchmarkVarint/signed_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_345.370000)-12     	 1000000	      1240 ns/op
BenchmarkVarint/signed_delta_varint/level_3_subtree_counts
BenchmarkVarint/signed_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)
BenchmarkVarint/signed_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)-12 	 1271079	       854.0 ns/op
BenchmarkVarint/signed_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_506.707000)
BenchmarkVarint/signed_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_506.707000)-12     	  731011	      1394 ns/op
BenchmarkVarint/signed_delta_varint/level_4_subtree_counts
BenchmarkVarint/signed_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)
BenchmarkVarint/signed_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)-12         	 1000000	      1087 ns/op
BenchmarkVarint/signed_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_667.735000)
BenchmarkVarint/signed_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_667.735000)-12                  	  590482	      2118 ns/op
BenchmarkVarint/min_delta_varint
BenchmarkVarint/min_delta_varint/level_1_subtree_counts
BenchmarkVarint/min_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)
BenchmarkVarint/min_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)-12                         	 1936206	       608.3 ns/op
BenchmarkVarint/min_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_184.606000)
BenchmarkVarint/min_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_184.606000)-12                     	 1568913	       701.7 ns/op
BenchmarkVarint/min_delta_varint/level_2_subtree_counts
BenchmarkVarint/min_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)
BenchmarkVarint/min_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)-12                     	 1273099	       846.2 ns/op
BenchmarkVarint/min_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_360.681000)
BenchmarkVarint/min_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_360.681000)-12                     	  895592	      1226 ns/op
BenchmarkVarint/min_delta_varint/level_3_subtree_counts
BenchmarkVarint/min_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)
BenchmarkVarint/min_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)-12                 	 1000000	      1150 ns/op
BenchmarkVarint/min_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_533.715000)
BenchmarkVarint/min_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_533.715000)-12                     	  736748	      1502 ns/op
BenchmarkVarint/min_delta_varint/level_4_subtree_counts
BenchmarkVarint/min_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)
BenchmarkVarint/min_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)-12            	 1041696	      1122 ns/op
BenchmarkVarint/min_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_702.628000)
BenchmarkVarint/min_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_702.628000)-12                     	  648548	      1757 ns/op
BenchmarkVarint/mean_delta_varint
BenchmarkVarint/mean_delta_varint/level_1_subtree_counts
BenchmarkVarint/mean_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)
BenchmarkVarint/mean_delta_varint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)-12                        	 2144900	       475.9 ns/op
BenchmarkVarint/mean_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_164.300000)
BenchmarkVarint/mean_delta_varint/level_1_subtree_counts/benchmark_decode_(mean_size:_164.300000)-12                    	 1613968	       718.2 ns/op
BenchmarkVarint/mean_delta_varint/level_2_subtree_counts
BenchmarkVarint/mean_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)
BenchmarkVarint/mean_delta_varint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)-12                    	 1754371	       661.9 ns/op
BenchmarkVarint/mean_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_323.129000)
BenchmarkVarint/mean_delta_varint/level_2_subtree_counts/benchmark_decode_(mean_size:_323.129000)-12                    	 1102936	      1212 ns/op
BenchmarkVarint/mean_delta_varint/level_3_subtree_counts
BenchmarkVarint/mean_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)
BenchmarkVarint/mean_delta_varint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)-12                	  986784	      1296 ns/op
BenchmarkVarint/mean_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_484.952000)
BenchmarkVarint/mean_delta_varint/level_3_subtree_counts/benchmark_decode_(mean_size:_484.952000)-12                    	  770954	      1686 ns/op
BenchmarkVarint/mean_delta_varint/level_4_subtree_counts
BenchmarkVarint/mean_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)
BenchmarkVarint/mean_delta_varint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)-12           	  891916	      1156 ns/op
BenchmarkVarint/mean_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_647.377000)
BenchmarkVarint/mean_delta_varint/level_4_subtree_counts/benchmark_decode_(mean_size:_647.377000)-12                    	  759640	      1592 ns/op
BenchmarkVarint/direct_varint
BenchmarkVarint/level_1_subtree_counts
BenchmarkVarint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)
BenchmarkVarint/level_1_subtree_counts/benchmark_encode_(mean:_150_std:_37)-12                                          	 2044312	       522.0 ns/op
BenchmarkVarint/level_1_subtree_counts/benchmark_decode_(mean_size:_258.822000)
BenchmarkVarint/level_1_subtree_counts/benchmark_decode_(mean_size:_258.822000)-12                                      	 1491814	       862.6 ns/op
BenchmarkVarint/level_2_subtree_counts
BenchmarkVarint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)
BenchmarkVarint/level_2_subtree_counts/benchmark_encode_(mean:_22500_std:_5625)-12                                      	 1965781	       606.1 ns/op
BenchmarkVarint/level_2_subtree_counts/benchmark_decode_(mean_size:_429.286000)
BenchmarkVarint/level_2_subtree_counts/benchmark_decode_(mean_size:_429.286000)-12                                      	 1401397	       781.7 ns/op
BenchmarkVarint/level_3_subtree_counts
BenchmarkVarint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)
BenchmarkVarint/level_3_subtree_counts/benchmark_encode_(mean:_3375000_std:_843750)-12                                  	 1903296	       565.2 ns/op
BenchmarkVarint/level_3_subtree_counts/benchmark_decode_(mean_size:_590.299000)
BenchmarkVarint/level_3_subtree_counts/benchmark_decode_(mean_size:_590.299000)-12                                      	 1292844	       884.0 ns/op
BenchmarkVarint/level_4_subtree_counts
BenchmarkVarint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)
BenchmarkVarint/level_4_subtree_counts/benchmark_encode_(mean:_506250000_std:_126562500)-12                             	 1738530	       623.7 ns/op
BenchmarkVarint/level_4_subtree_counts/benchmark_decode_(mean_size:_745.421000)
BenchmarkVarint/level_4_subtree_counts/benchmark_decode_(mean_size:_745.421000)-12                                      	  949071	      1063 ns/op
BenchmarkVarint/direct_varint-12                                                                                        	       1	14177712253 ns/op
PASS
```

**Pull request merged**
