### PR TITLE
[no-release-notes] bump for scope column pooling

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 80.03            | 81.48          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | eff9b9a2896bcc9fee654252ddc9f83ddd1ef4ab | 26.29 | tpcc-scale-factor-1 | dolt        | 099cd922d2fb7f30a8bfb52c1a6a1bcc336565ce | 26.01 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e27be75</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e27be75</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 81.48            | 82.96          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | eff9b9a2896bcc9fee654252ddc9f83ddd1ef4ab | 26.05 | tpcc-scale-factor-1 | dolt        | e27be75a8d1ae9b6c1076ffd504ec65c5d45f1d2 | 25.53 | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>88f8154</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>88f8154</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 81.48            | 81.48          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | eff9b9a2896bcc9fee654252ddc9f83ddd1ef4ab | 25.85 | tpcc-scale-factor-1 | dolt        | 88f815445d2553b897c576ed9f68636e333af4c0 | 25.92 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.97              | 0         |
| groupby_scan         | 17.01               | 17.01             | 0         |
| index_join           | 5.28                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.14              | 0         |
| index_scan           | 51.94               | 51.94             | 0         |
| oltp_point_select    | 0.49                | 0.48              | 0         |
| oltp_read_only       | 7.84                | 7.98              | 0         |
| select_random_points | 0.78                | 0.78              | 0         |
| select_random_ranges | 0.94                | 0.95              | 0         |
| table_scan           | 53.85               | 52.89             | 0         |
| types_table_scan     | 134.9               | 132.49            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.21              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 14.46               | 14.73             | 0         |
| oltp_update_index     | 3.13                | 3.13              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 6.43                | 6.55              | 0         |
| types_delete_insert   | 6.67                | 6.79              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 53.85               | 54.83             | 0         |
| oltp_point_select    | 0.51                | 0.5               | 0         |
| oltp_read_only       | 8.13                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 137.35              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.02                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.55                | 6.67              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.28                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.5                 | 0.5               | 0         |
| oltp_read_only       | 8.13                | 8.13              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 139.85              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.21              | 0         |
| oltp_insert           | 3.02                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.13              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 6.55                | 6.67              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Pull request closed without merging**
