### PR TITLE
[tree] return blob builders to pool after use

### PR DESCRIPTION
**Pull request by max-hoffman**
I added a builder pool and never returned the objects, this adds the Put().

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b024e60</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b024e60</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by max-hoffman** [comment]
#benchmark-import

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 99.33               | 97.55             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 9165f6b24ef1522a8a2eec6722b8f7b0b2462890 | 22.68 | tpcc-scale-factor-1 | dolt        | b024e602898d17c48f52544ff86e16b00e199973 | 22.8 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.07                | 3.02              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.28                | 5.18              | 0         |
| index_join_scan      | 2.26                | 2.22              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.52                | 0.52              | 0         |
| oltp_read_only       | 8.58                | 8.58              | 0         |
| select_random_points | 0.83                | 0.83              | 0         |
| select_random_ranges | 0.99                | 0.99              | 0         |
| table_scan           | 55.82               | 54.83             | 0         |
| types_table_scan     | 137.35              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.79                | 6.79              | 0         |
| oltp_insert           | 3.3                 | 3.3               | 0         |
| oltp_read_write       | 16.12               | 16.41             | 0         |
| oltp_update_index     | 3.55                | 3.55              | 0         |
| oltp_update_non_index | 3.49                | 3.49              | 0         |
| oltp_write_only       | 7.7                 | 7.7               | 0         |
| types_delete_insert   | 7.7                 | 7.7               | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d360df3</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d360df3</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by reltuk** [comment]
Are we missing a `bb.Reset()` or something on the builders that go back into (or come out of?) the pool?

Generally LGTM.

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7924fba</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7924fba</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>5c6afbe</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>5c6afbe</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0a97f9d</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0a97f9d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
