### PR TITLE
[no-release-notes] status update bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>1356e86</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>1356e86</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 66.84            | 66.84          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 6e515ad63d8364facf524e6084c5d39dbc51b6c3 | 36.04 | tpcc-scale-factor-1 | dolt        | 1356e86b88a6040da15133854284b0b7b32a08b7 | 37.02 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.97              | 0         |
| groupby_scan         | 17.01               | 16.71             | 0         |
| index_join           | 2.76                | 2.66              | 0         |
| index_join_scan      | 2.22                | 2.18              | 0         |
| index_scan           | 54.83               | 53.85             | 0         |
| oltp_point_select    | 0.44                | 0.4               | 0         |
| oltp_read_only       | 7.43                | 6.91              | 0         |
| select_random_points | 0.78                | 0.73              | 0         |
| select_random_ranges | 0.9                 | 0.87              | 0         |
| table_scan           | 55.82               | 53.85             | 0         |
| types_table_scan     | 147.61              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 13.7                | 12.75             | 0         |
| oltp_update_index     | 3.07                | 3.02              | 0         |
| oltp_update_non_index | 3.02                | 2.91              | 0         |
| oltp_write_only       | 6.21                | 6.09              | 0         |
| types_delete_insert   | 6.67                | 6.43              | 0         |

**Pull request closed without merging**
