### PR TITLE
[no-release-notes] bump for default sql mode

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 84.47            | 82.96          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 1c0ad8f76d869129ae37986a837395a9ad0e1368 | 25.43 | tpcc-scale-factor-1 | dolt        | dac551579ce868dc73018cc26b5618fca4b6aa33 | 25.5 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.5                 | 0.51              | 0         |
| oltp_read_only       | 8.13                | 8.13              | 0         |
| select_random_points | 0.8                 | 0.81              | 0         |
| select_random_ranges | 0.95                | 0.97              | 0         |
| table_scan           | 52.89               | 54.83             | 0         |
| types_table_scan     | 132.49              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.32              | 0         |
| oltp_insert           | 3.02                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.25              | 0         |
| oltp_update_non_index | 3.13                | 3.19              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 6.91                | 7.04              | 0         |

**Pull request closed without merging**
