### PR TITLE
[no-release-notes] Planbuilder Authorization changes

### PR DESCRIPTION
**Pull request by Hydrocharged**
* https://github.com/dolthub/go-mysql-server/pull/2712

### CODE REVIEW

**Comment by Hydrocharged** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3956678</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3956678</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 63.32            | 63.32          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | da3a5b8f3393fadb0edaa7b33e5b83c8e780fe72 | 40.75    | dolt           | 3956678f74995eac3230bdbc1f8fc65992774f07 | 41.05  | 0.74           |

**Comment by Hydrocharged** [comment]
* https://github.com/dolthub/doltgresql/pull/915

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.62         | 0.62       | 0.0            |
| groupby_scan         | 17.01        | 17.01      | 0.0            |
| index_join           | 2.35         | 2.35       | 0.0            |
| index_join_scan      | 1.89         | 1.89       | 0.0            |
| index_scan           | 54.83        | 55.82      | 1.81           |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.47         | 5.47       | 0.0            |
| select_random_points | 0.67         | 0.67       | 0.0            |
| select_random_ranges | 0.65         | 0.65       | 0.0            |
| table_scan           | 55.82        | 56.84      | 1.83           |
| types_table_scan     | 144.97       | 150.29     | 3.67           |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 5.88         | 5.88       | 0.0            |
| oltp_insert           | 2.91         | 2.91       | 0.0            |
| oltp_read_write       | 11.65        | 11.65      | 0.0            |
| oltp_update_index     | 2.97         | 2.97       | 0.0            |
| oltp_update_non_index | 2.91         | 2.91       | 0.0            |
| oltp_write_only       | 5.99         | 5.99       | 0.0            |
| types_delete_insert   | 6.43         | 6.32       | -1.71          |

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>762a15a</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>762a15a</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
