### PR TITLE
[no-release-notes] query flags bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d71671c</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d71671c</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.91              | 0         |
| groupby_scan         | 16.71               | 17.01             | 0         |
| index_join           | 2.76                | 2.66              | 0         |
| index_join_scan      | 2.22                | 2.18              | 0         |
| index_scan           | 54.83               | 53.85             | 0         |
| oltp_point_select    | 0.42                | 0.42              | 0         |
| oltp_read_only       | 7.3                 | 7.3               | 0         |
| select_random_points | 0.77                | 0.74              | 0         |
| select_random_ranges | 0.9                 | 0.87              | 0         |
| table_scan           | 55.82               | 53.85             | 0         |
| types_table_scan     | 144.97              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 13.46               | 13.22             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.21              | 0         |
| types_delete_insert   | 6.55                | 6.55              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 66.84            | 66.84          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 6e515ad63d8364facf524e6084c5d39dbc51b6c3 | 35.64 | tpcc-scale-factor-1 | dolt        | d71671c2e34b6baffa3f4973ebc663ac1f886fae | 36.92 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.86              | 0         |
| groupby_scan         | 17.01               | 16.71             | 0         |
| index_join           | 2.76                | 2.61              | 0         |
| index_join_scan      | 2.22                | 2.14              | 0         |
| index_scan           | 54.83               | 52.89             | 0         |
| oltp_point_select    | 0.44                | 0.41              | 0         |
| oltp_read_only       | 7.43                | 7.17              | 0         |
| select_random_points | 0.78                | 0.73              | 0         |
| select_random_ranges | 0.9                 | 0.86              | 0         |
| table_scan           | 55.82               | 53.85             | 0         |
| types_table_scan     | 144.97              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 5.88              | 0         |
| oltp_insert           | 3.02                | 2.97              | 0         |
| oltp_read_write       | 13.7                | 12.98             | 0         |
| oltp_update_index     | 3.07                | 3.02              | 0         |
| oltp_update_non_index | 3.02                | 2.97              | 0         |
| oltp_write_only       | 6.32                | 6.09              | 0         |
| types_delete_insert   | 6.67                | 6.43              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7ae6668</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7ae6668</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 68.05            | 64.47          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | c290ade4ea3035349fbea70af777bae497285ab0 | 36.57 | tpcc-scale-factor-1 | dolt        | 7ae6668ebc7a4502d018be37e08f3aaebecfb015 | 37.31 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.01               | 17.01             | 0         |
| index_join           | 2.66                | 2.61              | 0         |
| index_join_scan      | 2.18                | 2.11              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.41                | 0.39              | 0         |
| oltp_read_only       | 7.17                | 6.91              | 0         |
| select_random_points | 0.74                | 0.72              | 0         |
| select_random_ranges | 0.87                | 0.83              | 0         |
| table_scan           | 54.83               | 55.82             | 0         |
| types_table_scan     | 142.39              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.98               | 12.75             | 0         |
| oltp_update_index     | 2.97                | 2.97              | 0         |
| oltp_update_non_index | 2.91                | 2.91              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>39c39bb</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>39c39bb</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3e57bae</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3e57bae</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
