### PR TITLE
Fixes already on same branch error

### PR DESCRIPTION
**Pull request by VinaiRachakonda**
Addresses the issue here #1588

### CODE REVIEW

**Comment by VinaiRachakonda** [comment]
@andrew-wm-arthur Do you want this fixed for DOLT_CHECKOUT too?

**Comment by timsehn** [comment]
Again bats. It's the only way we know we won't break it again.

**Comment by timsehn** [comment]
bats comment retracted.

**Comment by andrew-wm-arthur** [comment]
@VinaiRachakonda Yes, we need the SQL function to match the CLI

**Review by andrew-wm-arthur — APPROVED** [review]
LGTM

**Pull request merged**
