### PR TITLE
Fixed spurious error message for event scheduling when the dolt_schem…

### PR DESCRIPTION
**Pull request by zachmu**
…as table doesn't exist.

### CODE REVIEW

**Review by fulghum — APPROVED** [review]
LGTM!

**Comment by coffeegoddd** [comment]
@zachmu __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.997743 to 99.996126</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>ee0270d</TD>
<TD>not ok</TD>
<TD>230</TD>
</TR>
<TR><TD>ee0270d</TD>
<TD>ok</TD>
<TD>5937227</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>ee0270d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.996126</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.997743 to 99.996126</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4786c57</TD>
<TD>not ok</TD>
<TD>230</TD>
</TR>
<TR><TD>4786c57</TD>
<TD>ok</TD>
<TD>5937227</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4786c57</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.996126</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@zachmu __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.997743 to 99.997743</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>8ac94d1</TD>
<TD>not ok</TD>
<TD>134</TD>
</TR>
<TR><TD>8ac94d1</TD>
<TD>ok</TD>
<TD>5937323</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>8ac94d1</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.997743</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.997743 to 99.997743</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>5f5202f</TD>
<TD>not ok</TD>
<TD>134</TD>
</TR>
<TR><TD>5f5202f</TD>
<TD>ok</TD>
<TD>5937323</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>5f5202f</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.997743</TD>
</TR>
</table>

**Pull request merged**
