### PR TITLE
[no-release-notes] bump for filter elide in select_random_points

### PR DESCRIPTION
**Pull request by max-hoffman**
re: https://github.com/dolthub/go-mysql-server/pull/2618

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>bc53ab9</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>bc53ab9</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 66.84            | 64.47          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | e8053d5649f43797dba05979a4618cca63ef906c | 37.28 | tpcc-scale-factor-1 | dolt        | bc53ab91a2dfef9d906019c33e9b1415e63a7c5b | 37.3 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.91              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 2.61                | 2.61              | 0         |
| index_join_scan      | 2.14                | 2.14              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.4                 | 0.39              | 0         |
| oltp_read_only       | 6.91                | 6.91              | 0         |
| select_random_points | 0.72                | 0.64              | 1         |
| select_random_ranges | 0.84                | 0.83              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.75               | 12.75             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.91                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Pull request closed without merging**
