### PR TITLE
[WIP] Ensure that the covering index properly leverages the primary key

### PR DESCRIPTION
**Pull request by VinaiRachakonda**

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Comment by VinaiRachakonda** [comment]
#benchmark

**Comment by timsehn** [comment]
Sweet perf win.

**Comment by VinaiRachakonda** [comment]
#benchmark

**Comment by VinaiRachakonda** [comment]
#benchmark

**Comment by VinaiRachakonda** [comment]
#benchmark

**Pull request closed without merging**
