### PR TITLE
Fixed handler bug related to ExtendedTypes

### PR DESCRIPTION
**Pull request by Hydrocharged**

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 99.999579</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a5f5896</TD>
<TD>not ok</TD>
<TD>25</TD>
</TR>
<TR><TD>a5f5896</TD>
<TD>ok</TD>
<TD>5937432</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a5f5896</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999579</TD>
</TR>
</table>

**Comment by Hydrocharged** [comment]
Ignore the failure here, need to merge main to get the updated correctness results.

**Comment by coffeegoddd** [comment]
@Hydrocharged __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e7d344b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e7d344b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by zachmu — APPROVED** [review]
LGTM

**Pull request merged**
