### PR TITLE
Diff based foreign key validation

### PR DESCRIPTION
**Pull request by bheni**
Previous validation implementation did full scans for every foreign key constraint.  New implementation only validates against rows that have changed from the previous commit.

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
The idea here seems sound, but could we diff the FK indexes directly instead of diffing the row storage and looking for changes in the FK columns?

**Comment by bheni** [comment]
@andrew-wm-arthur yeah, that's better.

**Comment by Hydrocharged** [comment]
Since Brian will change the logic a bit, I’ll wait to review.

**Review by andrew-wm-arthur — APPROVED** [review]
looks good, but we need more error-case tests

**Review by Hydrocharged — APPROVED** [review]
LGTM as well

**Pull request merged**
