### PR TITLE
match mysql fk name generation

### PR DESCRIPTION
**Pull request by jycor**
This PR removes logic where we would use a consistent hash to create foreign key names, when one isn't explicitly provided.
Instead, we use logic in GMS to generate a name with the template `"<tbl_name>_ibfk_<num>"`, which matches MySQL behavior.

As a result, we now allow multiple foreign keys over the same sets of columns (as long as the names are different).

companion pr:
https://github.com/dolthub/go-mysql-server/pull/2438

fixes:
https://github.com/dolthub/dolt/issues/7650

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c48d7a7</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c48d7a7</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e1ef2eb</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e1ef2eb</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by fulghum — APPROVED** [review]
Looks good! 

It's a bummer to lose the ability for two branches to both add an FK constraint or secondary index to the same table and merge them back cleanly – that is a cool trick. I think being MySQL compatible ultimately wins out here though, especially since we are giving customers a new statement to easily rename a constraint, and since customers can explicitly specify constraint names to get around the merge conflict issue. 

We *may* eventually want to support both modes, but that's adding complexity for users to deal with, so I'd hold off on that until we know it's definitely a customer problem we need to work on. 

Tagging @zachmu on this one, since he may have an opinion on the tradeoff between fully matching MySQL's behavior and keeping the deterministic fk / secondary index naming. Since the customer isn't blocked on this currently, let's give Zach a day to share an opinion, just in case he sees another problem this could cause that we aren't seeing.

**Review by zachmu — APPROVED** [review]
LGTM, see comments on GMS change

**Review by zachmu — COMMENTED** [review]
But write tests of merge logic (can skip for now)

If two sides of the merge declare the same fk name with a different definition, that should be a schema conflict.

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>bfd7282</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>bfd7282</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
