### PR TITLE
Max/tonicai bats

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by timsehn** [comment]
This is already making me really, really happy.

**Review by zachmu — COMMENTED** [review]
Identified other problematic statements:

```
// these may or may not work process, but they definitely won't do anything
SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;

// these might work or might not
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */
/*!40103 SET TIME_ZONE='+00:00' */
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */

// this will parse fine, but if they expect it to do something that
// might be a problem (we don't support changing the character set)
/*!40101 SET character_set_client = utf8 */

// empty info schema tables, may or may not be a problem
FROM information_schema.table_constraints AS tc // partial query
JOIN information_schema.key_column_usage AS kcu // partial query
information_schema.STATISTICS

// this may or may not process, but it won't do anything
SET net_write_timeout=1800;
SET net_read_timeout=1800;
```

**Comment by timsehn** [comment]
Can we merge this? Seems like it's passing now. @VinaiRachakonda

**Comment by VinaiRachakonda** [comment]
@timsehn Easier to just delete the branch.  These tests have bugs. Since it's a draft the CI wasn't run

**Comment by timsehn** [comment]
Either make sure the tests are covered in your other work and delete or fix
it and merge this one.

**Review by VinaiRachakonda — APPROVED** [review]

**Pull request merged**
