### PR TITLE
[TESTING] Benchmark privilege cache changes

### PR DESCRIPTION
**Pull request by Hydrocharged**

### CODE REVIEW

**Comment by Hydrocharged** [comment]
#benchmark

**Comment by Hydrocharged** [comment]
#benchmark

**Comment by Hydrocharged** [comment]
#benchmark

**Comment by timsehn** [comment]
Beautiful!

**Comment by timsehn** [comment]
On second look. Not beautiful.

**Comment by Hydrocharged** [comment]
There shouldn’t really be a difference between the two. I’m trading a map lookup for a mutex lock as far as time complexity goes, but I don’t know if the lock is even necessary. I’ll try removing it and seeing if it makes a difference.

**Comment by Hydrocharged** [comment]
#benchmark

**Comment by Hydrocharged** [comment]
There is a lot of run-to-run variance, so it looks like any improvements or regressions are within the margin of error.

**Pull request closed without merging**
