### PR TITLE
Reuse DoltEnv when creating MultiEnv

### PR DESCRIPTION
**Pull request by nicktobey**
I thought this would speed up startup latency by as much as 50% when garbage hasn't been collected in a while. Previously we were loading the environment (including the index) from disk twice. Now we only do it once.

It turns out that reading from the db is cached so this won't actually affect startup latency. But it simplifies the code flow in most cases.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4b0928a</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4b0928a</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e07e403</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e07e403</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c3506c8</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c3506c8</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9330687</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9330687</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by reltuk** [comment]
Just my opinion, but the naked boolean parameter, having to choose its value at the call site correctly, having to check for certain error conditions and nil out error states on the dEnv, etc. I think it's a little hard to argue this change simplifies the code.

I do think it's confusing to have multiple dEnv instances floating around for the same directory on disk, and for those to have been loaded at different times in the application's lifecycle, etc. I'm just not certain that this change in particular actually simplifies the code. That being said, it might still be worth it if we're concerned about the runtime behavior, the potential for confusion between the instances, etc.

Even with this change, things seem quite subtle and hard to get right. Are the less subtle now than before? As someone who's not close to it at all and has only read over the PR, it's hard for me in particular to say.

**Comment by fulghum** [comment]
I agree with Aaron. The change looks correct of course, but I'm not convinced it's worth merging in unless there was some customer benefit like a performance improvement. For me, the extra boolean param makes it a little harder to call `MultiEnvForDirectory` correctly, and even after reading the code, I couldn't tell you why we need to pass `true` in one place, but nowhere else. I think the current version (where we reload the main env) is simpler to call, easier to call correctly, and still has the same performance characteristics.

**Comment by nicktobey** [comment]
I agree with your comments. While this technically avoids some redundant logic, it adds its own complexity, and without a clear benefit (such as a performance improvement), there's no compelling reason to merge it.

**Pull request closed without merging**
