### PR TITLE
[no-release-notes] Bug fix bump, small stats bug

### PR DESCRIPTION
**Pull request by max-hoffman**
see: https://github.com/dolthub/go-mysql-server/pull/2583. The changes in this PR are not load-bearing.

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 74.46            | 75.82          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | bcf4dd5f5cc1ca460a1712305d499b26f6036f1f | 33.12 | tpcc-scale-factor-1 | dolt        | 942f85e6d4646240381b79f53e48fe94b875e7c7 | 32.86 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>cef7c10</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>cef7c10</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.86                | 2.86              | 0         |
| groupby_scan         | 17.32               | 17.63             | 0         |
| index_join           | 5.18                | 5.37              | 0         |
| index_join_scan      | 2.61                | 2.57              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.46                | 0.46              | 0         |
| oltp_read_only       | 7.7                 | 7.7               | 0         |
| select_random_points | 0.75                | 0.75              | 0         |
| select_random_ranges | 0.9                 | 0.89              | 0         |
| table_scan           | 55.82               | 56.84             | 0         |
| types_table_scan     | 144.97              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 14.21               | 13.95             | 0         |
| oltp_update_index     | 3.07                | 3.07              | 0         |
| oltp_update_non_index | 3.02                | 3.02              | 0         |
| oltp_write_only       | 6.43                | 6.43              | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Pull request merged**
