### PR TITLE
[no-release-notes] skip more wire allocs

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 57.87            | 61.08          | 5.55           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 58d462690dca394ef11888367fb063666df3de51 | 40.96    | dolt           | 2e9d2efe7cb9e7ca564efd62329444290a485a82 | 40.24  | -1.76          |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.61         | 0.62       | 1.64           |
| groupby_scan         | 16.12        | 16.71      | 3.66           |
| index_join           | 2.26         | 2.3        | 1.77           |
| index_join_scan      | 1.39         | 1.47       | 5.76           |
| index_scan           | 50.11        | 43.39      | -13.41         |
| oltp_point_select    | 0.26         | 0.27       | 3.85           |
| oltp_read_only       | 5.28         | 5.37       | 1.7            |
| select_random_points | 0.63         | 0.64       | 1.59           |
| select_random_ranges | 0.63         | 0.65       | 3.17           |
| table_scan           | 50.11        | 43.39      | -13.41         |
| types_table_scan     | 137.35       | 114.72     | -16.48         |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.09         | 6.21       | 1.97           |
| oltp_insert           | 3.02         | 3.07       | 1.66           |
| oltp_read_write       | 11.45        | 11.65      | 1.75           |
| oltp_update_index     | 3.07         | 3.13       | 1.95           |
| oltp_update_non_index | 3.02         | 3.02       | 0.0            |
| oltp_write_only       | 6.09         | 6.21       | 1.97           |
| types_delete_insert   | 6.43         | 6.55       | 1.87           |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>133b582</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>133b582</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | -1.78          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | ffd5bde4c4a62abad17314797e0e55b83e25b1db | 39.43    | dolt           | 8713fecff7b97bc921a53a4fdbb79763f3b9de3e | 39.81  | 0.96           |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.62         | 0.62       | 0.0            |
| groupby_scan         | 16.41        | 17.01      | 3.66           |
| index_join           | 2.3          | 2.35       | 2.17           |
| index_join_scan      | 1.42         | 1.47       | 3.52           |
| index_scan           | 51.94        | 42.61      | -17.96         |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.47         | 5.37       | -1.83          |
| select_random_points | 0.65         | 0.65       | 0.0            |
| select_random_ranges | 0.65         | 0.65       | 0.0            |
| table_scan           | 51.94        | 43.39      | -16.46         |
| types_table_scan     | 139.85       | 112.67     | -19.44         |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.21         | 6.32       | 1.77           |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.87        | 11.65      | -1.85          |
| oltp_update_index     | 3.13         | 3.13       | 0.0            |
| oltp_update_non_index | 3.07         | 3.07       | 0.0            |
| oltp_write_only       | 6.32         | 6.32       | 0.0            |
| types_delete_insert   | 6.55         | 6.55       | 0.0            |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d115e67</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d115e67</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>6ac6ed5</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>6ac6ed5</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
