### PR TITLE
[no-release-notes] another max1row iter

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d04dd05</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d04dd05</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 65.65            | 65.65          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 2e109649527495e541ef3f27e2f2a99f7493d79c | 37.85 | tpcc-scale-factor-1 | dolt        | d04dd053be8441bebd08e495eff5a313be3d333f | 37.48 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.01               | 17.01             | 0         |
| index_join           | 2.66                | 2.61              | 0         |
| index_join_scan      | 2.14                | 2.14              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.39                | 0.39              | 0         |
| oltp_read_only       | 6.91                | 6.91              | 0         |
| select_random_points | 0.72                | 0.72              | 0         |
| select_random_ranges | 0.84                | 0.83              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.75               | 12.75             | 0         |
| oltp_update_index     | 2.97                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 63.32            | 70.55          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | fac6cd4a8cda5343e4c86d5edb51b0471afd5930 | 37.51 | tpcc-scale-factor-1 | dolt        | b83f3a109a88fc380a2b0fc7d964d46a70c2621d | 35.54 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>f45d76e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>f45d76e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.07              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 2.61                | 2.81              | 0         |
| index_join_scan      | 2.14                | 2.26              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.39                | 0.37              | 0         |
| oltp_read_only       | 6.91                | 7.17              | 0         |
| select_random_points | 0.72                | 0.81              | -1        |
| select_random_ranges | 0.83                | 0.92              | -1        |
| table_scan           | 54.83               | 53.85             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 6.09              | 0         |
| oltp_insert           | 2.91                | 3.02              | 0         |
| oltp_read_write       | 12.75               | 13.22             | 0         |
| oltp_update_index     | 2.97                | 3.07              | 0         |
| oltp_update_non_index | 2.91                | 3.02              | 0         |
| oltp_write_only       | 6.09                | 6.32              | 0         |
| types_delete_insert   | 6.43                | 6.55              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 64.47            | 71.83          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | fac6cd4a8cda5343e4c86d5edb51b0471afd5930 | 37.45 | tpcc-scale-factor-1 | dolt        | f45d76ea07946285f6e2269e97b0e64b9608725f | 35.33 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 3.07              | 0         |
| groupby_scan         | 17.01               | 17.63             | 0         |
| index_join           | 2.61                | 2.81              | 0         |
| index_join_scan      | 2.11                | 2.26              | 0         |
| index_scan           | 52.89               | 53.85             | 0         |
| oltp_point_select    | 0.38                | 0.37              | 0         |
| oltp_read_only       | 6.67                | 7.17              | 0         |
| select_random_points | 0.7                 | 0.81              | -1        |
| select_random_ranges | 0.81                | 0.92              | -1        |
| table_scan           | 52.89               | 54.83             | 0         |
| types_table_scan     | 137.35              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 6.09              | 0         |
| oltp_insert           | 2.97                | 3.07              | 0         |
| oltp_read_write       | 12.52               | 12.98             | 0         |
| oltp_update_index     | 2.97                | 3.13              | 0         |
| oltp_update_non_index | 2.91                | 3.07              | 0         |
| oltp_write_only       | 6.09                | 6.55              | 0         |
| types_delete_insert   | 6.43                | 6.67              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e280e3f</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e280e3f</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 65.65            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | fac6cd4a8cda5343e4c86d5edb51b0471afd5930 | 37.33 | tpcc-scale-factor-1 | dolt        | e280e3fb19eeeea895107cfcfab58d2f6f1c45aa | 39.28 | 0         |

**Review by nicktobey — APPROVED** [review]

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 2.66                | 2.66              | 0         |
| index_join_scan      | 2.14                | 2.14              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.39                | 0.3               | 1         |
| oltp_read_only       | 6.91                | 5.88              | 1         |
| select_random_points | 0.72                | 0.73              | 0         |
| select_random_ranges | 0.83                | 0.83              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.75               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d2c5f5c</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d2c5f5c</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
