### PR TITLE
[no-release-notes] bump for stats perf

### PR DESCRIPTION
**Pull request by max-hoffman**
companion: https://github.com/dolthub/go-mysql-server/pull/2555

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>30dbecc</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>30dbecc</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 82.96            | 75.82          | 0         |


|      test_name      | server_name |              server_version              | tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 3ea7e6928cf241c9dc59783dd25ddc00d924811c | 25.7 | tpcc-scale-factor-1 | dolt        | 30dbecc8788a862b9f03d317bf105e23a6f173a7 | 28.88 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.81                | 2.81              | 0         |
| groupby_scan         | 17.32               | 17.01             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 10.84               | 3.25              | 1         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.46                | 0.46              | 0         |
| oltp_read_only       | 7.56                | 7.56              | 0         |
| select_random_points | 0.77                | 0.75              | 0         |
| select_random_ranges | 0.92                | 0.9               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 142.39              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 13.95               | 13.95             | 0         |
| oltp_update_index     | 3.07                | 3.13              | 0         |
| oltp_update_non_index | 3.02                | 3.02              | 0         |
| oltp_write_only       | 6.43                | 6.43              | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Comment by timsehn** [comment]
image

Better but still not 2.2 like it was before.

**Pull request merged**
