### PR TITLE
[no-release-notes] tracing infra

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a197712</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a197712</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 84.47            | 81.48          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 69d9d977ea11fbc865622cad83904aedab3a9c94 | 25.53 | tpcc-scale-factor-1 | dolt        | a19771292b946bfbddd44acfd8569b09d7a88fff | 25.9 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.02                | 3.07              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.47                | 5.47              | 0         |
| index_join_scan      | 2.22                | 2.26              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.52                | 0.51              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.83                | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.94              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 139.85              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.13                | 3.13              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 6.55                | 6.55              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Review by fulghum — APPROVED** [review]
LGTM

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>8df0e47</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>8df0e47</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b66b5f1</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b66b5f1</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
