### PR TITLE
chore: use errors.New to replace fmt.Errorf with no parameters

### PR DESCRIPTION
**Pull request by ChengenH**

### CODE REVIEW

**Comment by timsehn** [comment]
Thanks for the contribution. @jycor will look at this.

**Review by jycor — CHANGES_REQUESTED** [review]
Hey @ChengenH, thanks for the contribution and tidying up our errors.

The changes mostly look good, but some files are missing the `"errors"` import.
I think adding the missing import to:
- `go/cmd/dolt/cli/cli_context.go`
- `go/cmd/dolt/commands/cnfcmds/conflictsplitter.go`
- `go/cmd/dolt/commands/docscmds/write.go`
- `go/cmd/dolt/commands/engine/sql_print.go`

Will be happy to approve once those are in!

**Comment by ChengenH** [comment]
> Hey @ChengenH, thanks for the contribution and tidying up our errors.
> 
> The changes mostly look good, but some files are missing the `"errors"` import. I think adding the missing import to:
> 
> * `go/cmd/dolt/cli/cli_context.go`
> * `go/cmd/dolt/commands/cnfcmds/conflictsplitter.go`
> * `go/cmd/dolt/commands/docscmds/write.go`
> * `go/cmd/dolt/commands/engine/sql_print.go`
> 
> Will be happy to approve once those are in!

Sorry, I missed it. I have added it now.

**Comment by timsehn** [comment]
Running tests now.

**Review by jycor — APPROVED** [review]
LGTM

**Pull request merged**
