### PR TITLE
[no-release-notes] bump for ITA fast assign

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 86.0             | 86.0           | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 1c0ad8f76d869129ae37986a837395a9ad0e1368 | 24.91 | tpcc-scale-factor-1 | dolt        | 75b6b12251bfbace8087ffa706c35eab6d1a9d09 | 24.88 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 84.47            | 82.96          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 1c0ad8f76d869129ae37986a837395a9ad0e1368 | 25.44 | tpcc-scale-factor-1 | dolt        | f9525dc34b85780f12ccaa9bb7a51c1680ba2999 | 25.34 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.28                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 7.04                | 6.91              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.18                | 5.28              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 53.85               | 54.83             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 6.91                | 6.91              | 0         |

**Pull request closed without merging**
