### PR TITLE
Migrate dolt table cp/mv/rm commands to SQL

### PR DESCRIPTION
**Pull request by PavelSafronov**
Migrate `dolt table cp`/`dolt table mv`/`dolt table rm` to use SQL.

This change also adds a new convenience method, InterpolateAndRunQuery, which can be used to interpolate a query, execute the query, and get all the result rows. Since this method does not return a schema, this method is useful only for fire-and-forget types of queries.

### CODE REVIEW

**Review by macneale4 — CHANGES_REQUESTED** [review]
What the test coverage status for this command? A new test in sql-local-remote.bats is needed

**Comment by PavelSafronov** [comment]
> What the test coverage status for this command? A new test in sql-local-remote.bats is needed

Added sql-local-remote.bats tests

**Comment by PavelSafronov** [comment]
This is only a partial migration of `dolt table`, as we're not yet migrating `dolt table import` and `dolt table export`.
This PR is being marked as Draft and will be resurrected when we are ready to migrate the entire `dolt table` command.

**Comment by macneale4** [comment]
Preserving the branch: https://github.com/dolthub/dolt/tree/pavel/migrate-dolt-table-cp-mv-rm

There are several other issued to work out with the `table` command, and these will wait until we get there.

**Pull request closed without merging**
