### PR TITLE
[types] cache frequently read value store chunks (like working set roots)

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>6d28daf</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>6d28daf</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 82.96            | 81.48          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 0f351c40892a119a2fe247c00b8805e21520aa08 | 25.59 | tpcc-scale-factor-1 | dolt        | 6d28daf3061e654f1e507b7b36fb602a8b3b4c43 | 25.6 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.37                | 5.47              | 0         |
| index_join_scan      | 2.26                | 2.26              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.52                | 0.52              | 0         |
| oltp_read_only       | 8.28                | 8.43              | 0         |
| select_random_points | 0.83                | 0.83              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 139.85              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.02              | 0         |
| oltp_read_write       | 15.27               | 15.27             | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.07              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 6.91                | 6.79              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>065749a</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>065749a</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
