### PR TITLE
insert perf bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>978128b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>978128b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 97.55             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 12335605bc803f151fc5d85c612341b56549488b | 22.54 | tpcc-scale-factor-1 | dolt        | 978128bac1cdc1defe2e6b58c17ecadc21be4e5f | 22.66 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.26              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.43                | 8.43              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 53.85               | 54.83             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.91              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.12               | 16.12             | 0         |
| oltp_update_index     | 3.55                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.84              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>50a2fa8</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>50a2fa8</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 95.81             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 12335605bc803f151fc5d85c612341b56549488b | 22.81 | tpcc-scale-factor-1 | dolt        | 50a2fa80a487d8698517df4cbda60b7209e8db5d | 23.09 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.09                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.5                 | 0.51              | 0         |
| oltp_read_only       | 8.43                | 8.43              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.95                | 0.95              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 137.35              | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.79                | 6.79              | 0         |
| oltp_insert           | 3.43                | 3.36              | 0         |
| oltp_read_write       | 16.12               | 16.12             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.84              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>46e72b5</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>46e72b5</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 95.81             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 12335605bc803f151fc5d85c612341b56549488b | 22.63 | tpcc-scale-factor-1 | dolt        | 46e72b58e82c5007cce25c6954ad623565b96b5e | 22.81 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.91              | 0         |
| groupby_scan         | 17.63               | 17.32             | 0         |
| index_join           | 5.18                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.18              | 0         |
| index_scan           | 52.89               | 51.94             | 0         |
| oltp_point_select    | 0.51                | 0.49              | 0         |
| oltp_read_only       | 8.43                | 8.13              | 0         |
| select_random_points | 0.8                 | 0.78              | 0         |
| select_random_ranges | 0.95                | 0.94              | 0         |
| table_scan           | 54.83               | 52.89             | 0         |
| types_table_scan     | 137.35              | 132.49            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.79                | 6.67              | 0         |
| oltp_insert           | 3.43                | 3.25              | 0         |
| oltp_read_write       | 16.12               | 15.55             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.43              | 0         |
| types_delete_insert   | 7.56                | 7.43              | 0         |

**Comment by max-hoffman** [comment]
- [ ]

**Pull request closed without merging**
