### PR TITLE
Pass `nil` `sql.QueryFlags` to `planbuilder.Binder` and bump

### PR DESCRIPTION
**Pull request by jycor**
companion pr: https://github.com/dolthub/go-mysql-server/pull/2676

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>06a682b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>06a682b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>f966d35</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>f966d35</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by jycor** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e2a8133</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e2a8133</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.68                | 0.65              | 0         |
| groupby_scan         | 16.71               | 16.41             | 0         |
| index_join           | 2.66                | 2.52              | 0         |
| index_join_scan      | 2.11                | 2.03              | 0         |
| index_scan           | 55.82               | 54.83             | 0         |
| oltp_point_select    | 0.3                 | 0.29              | 0         |
| oltp_read_only       | 5.77                | 5.67              | 0         |
| select_random_points | 0.65                | 0.68              | 0         |
| select_random_ranges | 0.7                 | 0.69              | 0         |
| table_scan           | 55.82               | 54.83             | 0         |
| types_table_scan     | 147.61              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.65             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.91              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0c9746d</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0c9746d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.67              | 0         |
| groupby_scan         | 16.71               | 16.71             | 0         |
| index_join           | 2.52                | 2.57              | 0         |
| index_join_scan      | 2.03                | 2.11              | 0         |
| index_scan           | 55.82               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.88              | 0         |
| select_random_points | 0.7                 | 0.7               | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 144.97              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 471d129e85ffcab0cb1d36996ed6b971365cdb06 | 39.17 | tpcc-scale-factor-1 | dolt        | 0c9746db8fcc82adc590ad6ced715c0273433c27 | 39.17 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a92372e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a92372e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.67              | 0         |
| groupby_scan         | 16.41               | 16.41             | 0         |
| index_join           | 2.52                | 2.52              | 0         |
| index_join_scan      | 2.07                | 2.07              | 0         |
| index_scan           | 54.83               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.88              | 0         |
| select_random_points | 0.7                 | 0.7               | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 144.97              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 2.97              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c08957b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c08957b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 62.19          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 39.03 | tpcc-scale-factor-1 | dolt        | c08957bbaa8130aaab2833f092203995bbf9bb3f | 38.94 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.65                | 0.68              | 0         |
| groupby_scan         | 16.41               | 17.01             | 0         |
| index_join           | 2.52                | 2.57              | 0         |
| index_join_scan      | 2.07                | 2.11              | 0         |
| index_scan           | 54.83               | 55.82             | 0         |
| oltp_point_select    | 0.28                | 0.3               | 0         |
| oltp_read_only       | 5.77                | 5.88              | 0         |
| select_random_points | 0.68                | 0.7               | 0         |
| select_random_ranges | 0.69                | 0.7               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 142.39              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.91                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.87             | 0         |
| oltp_update_index     | 2.97                | 3.02              | 0         |
| oltp_update_non_index | 2.91                | 2.97              | 0         |
| oltp_write_only       | 5.99                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 63.32          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 39.33 | tpcc-scale-factor-1 | dolt        | bc85b38251822ea981790b264e8634df100a6881 | 39.29 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.68              | 0         |
| groupby_scan         | 16.41               | 17.01             | 0         |
| index_join           | 2.52                | 2.48              | 0         |
| index_join_scan      | 2.07                | 2.0               | 0         |
| index_scan           | 54.83               | 55.82             | 0         |
| oltp_point_select    | 0.29                | 0.3               | 0         |
| oltp_read_only       | 5.77                | 5.77              | 0         |
| select_random_points | 0.69                | 0.65              | 0         |
| select_random_ranges | 0.69                | 0.7               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 142.39              | 147.61            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 3.02              | 0         |
| oltp_read_write       | 11.87               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.55              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>339fd34</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>339fd34</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 39.63 | tpcc-scale-factor-1 | dolt        | 339fd347b4af6bf9a1e81fb528301f148e46e9d1 | 39.63 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.68              | 0         |
| groupby_scan         | 16.71               | 17.32             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.07                | 2.0               | 0         |
| index_scan           | 55.82               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.67              | 0         |
| select_random_points | 0.69                | 0.64              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 147.61              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.65             | 0         |
| oltp_update_index     | 2.97                | 3.02              | 0         |
| oltp_update_non_index | 2.91                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>bdafaa1</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>bdafaa1</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 69.29            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 37.28 | tpcc-scale-factor-1 | dolt        | bdafaa1b9b6864e00ab4c3a0135a27d283f172e8 | 38.61 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.68              | 0         |
| groupby_scan         | 16.41               | 16.71             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.11                | 2.07              | 0         |
| index_scan           | 55.82               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.77              | 0         |
| select_random_points | 0.7                 | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 56.84               | 56.84             | 0         |
| types_table_scan     | 150.29              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9e6618e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9e6618e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>ce8d961</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>ce8d961</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 58.92            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | fdd24549db05b6c9277d6bc959a4e4e84f8738dc | 40.47 | tpcc-scale-factor-1 | dolt        | ce8d961f5c541747f93c591508b3a32f2faf350b | 39.6 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.68                | 0.68              | 0         |
| groupby_scan         | 16.41               | 16.71             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.11                | 2.0               | 0         |
| index_scan           | 56.84               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.77              | 0         |
| select_random_points | 0.7                 | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 56.84               | 55.82             | 0         |
| types_table_scan     | 147.61              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.88              | 0         |
| oltp_insert           | 2.91                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.65             | 0         |
| oltp_update_index     | 2.97                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>ac4147f</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>ac4147f</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 63.32            | 63.32          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | fdd24549db05b6c9277d6bc959a4e4e84f8738dc | 39.36 | tpcc-scale-factor-1 | dolt        | ac4147f8a072d1a4d6ad618fba43053c8bc962da | 39.56 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.68                | 0.68              | 0         |
| groupby_scan         | 16.41               | 16.71             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.11                | 1.96              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.77              | 0         |
| select_random_points | 0.7                 | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 55.82               | 54.83             | 0         |
| types_table_scan     | 144.97              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>52407a3</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>52407a3</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | b407a9c5e10e746dd5863845fa740c347f501943 | 39.36 | tpcc-scale-factor-1 | dolt        | 52407a3f69327018907259c83c6e66c6d44143a9 | 39.33 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.68                | 0.68              | 0         |
| groupby_scan         | 16.41               | 17.01             | 0         |
| index_join           | 2.57                | 2.35              | 0         |
| index_join_scan      | 2.11                | 1.89              | 1         |
| index_scan           | 56.84               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.99                | 5.77              | 0         |
| select_random_points | 0.7                 | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 56.84               | 55.82             | 0         |
| types_table_scan     | 147.61              | 147.61            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 3.02              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.21              | 0         |
| types_delete_insert   | 6.55                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c3b7aba</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c3b7aba</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
