### PR TITLE
[no-release-notes] parser perf bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0ec801d</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0ec801d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percentage_change |
|---------------------|------------------|----------------|-------------------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | 1.78              |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percentage_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|-------------------|
| tpcc-scale-factor-1 | dolt             | 283d69339e2184fbfb07ef0aa657fc0fb8dee87a | 39.53    | dolt           | 0ec801de2d8f8c052cd91a4c93f72574990cab8a | 41.41  | -4.76             |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.64         | 0.64       | 0.0            |
| groupby_scan         | 16.71        | 17.01      | -1.8           |
| index_join           | 2.35         | 2.35       | 0.0            |
| index_join_scan      | 1.89         | 1.89       | 0.0            |
| index_scan           | 55.82        | 54.83      | 1.77           |
| oltp_point_select    | 0.3          | 0.27       | 10.0           |
| oltp_read_only       | 5.67         | 5.47       | 3.53           |
| select_random_points | 0.64         | 0.61       | 4.69           |
| select_random_ranges | 0.7          | 0.63       | 10.0           |
| table_scan           | 56.84        | 55.82      | 1.79           |
| types_table_scan     | 147.61       | 144.97     | 1.79           |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 5.99         | 5.88       | 1.84           |
| oltp_insert           | 2.97         | 2.91       | 2.02           |
| oltp_read_write       | 11.65        | 11.24      | 3.52           |
| oltp_update_index     | 3.02         | 2.97       | 1.66           |
| oltp_update_non_index | 2.97         | 2.91       | 2.02           |
| oltp_write_only       | 6.09         | 5.99       | 1.64           |
| types_delete_insert   | 6.43         | 6.32       | 1.71           |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>479d73d</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>479d73d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 64.47            | 59.99          | -6.95          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 670865ae659a750687653bf2512a85affa95a464 | 39.26    | dolt           | 479d73dd5ce02cef61fa3575ebff16345743bbd3 | 41.25  | 5.07           |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.65         | 0.62       | -4.62          |
| groupby_scan         | 17.01        | 16.71      | -1.76          |
| index_join           | 2.39         | 2.35       | -1.67          |
| index_join_scan      | 1.96         | 1.86       | -5.1           |
| index_scan           | 55.82        | 54.83      | -1.77          |
| oltp_point_select    | 0.3          | 0.27       | -10.0          |
| oltp_read_only       | 5.77         | 5.47       | -5.2           |
| select_random_points | 0.65         | 0.61       | -6.15          |
| select_random_ranges | 0.7          | 0.62       | -11.43         |
| table_scan           | 56.84        | 55.82      | -1.79          |
| types_table_scan     | 147.61       | 144.97     | -1.79          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 5.99         | 5.88       | -1.84          |
| oltp_insert           | 2.97         | 2.91       | -2.02          |
| oltp_read_write       | 11.87        | 11.24      | -5.31          |
| oltp_update_index     | 3.02         | 2.97       | -1.66          |
| oltp_update_non_index | 2.97         | 2.91       | -2.02          |
| oltp_write_only       | 6.21         | 5.88       | -5.31          |
| types_delete_insert   | 6.55         | 6.32       | -3.51          |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a3984b7</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a3984b7</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by zachmu — APPROVED** [review]

**Pull request closed without merging**
