### PR TITLE
tuple type changes

### PR DESCRIPTION
**Pull request by bheni**

### CODE REVIEW

**Comment by bheni** [comment]
#benchmark

**Review by zachmu — APPROVED** [review]
image

**Review by Hydrocharged — APPROVED** [review]
Looks fine to me as well

**Comment by timsehn** [comment]
This looks like a real nice write throughput win across the board.

**Review by andrew-wm-arthur — APPROVED** [review]
Seems like we should do this. My only concern is diff perf. Changing the types we serialize in meta-tuples will change the content-addresses of the internal nodes. You could have equal two subtrees that have different root addresses, one written with the old types and one written with the new. However, this will phase out over time and this change won't affect the addresses of leaf nodes, so we'll still skip over them when equal.

**Comment by timsehn** [comment]
What are we doing to advance the ball here?

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Comment by zachmu** [comment]
#benchmark

**Comment by timsehn** [comment]
Let's ship this.

**Comment by timsehn** [comment]
And worth a blog.

**Comment by Hydrocharged** [comment]
@bheni So I've run this with merging on the fuzzer (rebased onto the `master`) and it seems good to go! I think we can finally get this into Dolt.

**Pull request merged**
