### PR TITLE
libraries/doltcore/doltdb: fix dropped errors

### PR DESCRIPTION
**Pull request by alrs**
This fixes dropped errors in `libraries/doltcore/doltdb`.

### CODE REVIEW

**Comment by alrs** [comment]
Am I looking at an actual Bats-failure, or a flake?

**Comment by timsehn** [comment]
Seems like a flake. Sorry for not being on top of this.

@coffeegoddd do you mind kicking these off again?

**Comment by timsehn** [comment]
Kicked it in the pants. @zachmu will review when/if it passes...

**Comment by timsehn** [comment]
I think this may be failing for a valid reason. We've tried three times.

**Comment by timsehn** [comment]
Looks like a true bug.

```
not ok 77 back-compat: table operations
# (in test file ./back-compat.bats, line 73)
#   'dolt table cp abc copy' failed
# Successfully initialized dolt data repository.
# error on line 1 for query CREATE TABLE `copy` LIKE `abc`: tag collision for columns pk and doc_name, different definitions (tag: 0)
# Error processing batch
```

**Comment by zachmu** [comment]
Thanks for the catch, Lars. You caught a bug!

I skipped the test and cleaned up the error return style in https://github.com/dolthub/dolt/pull/1481. I'll merge that in once it passes CI.

Thanks again!

**Pull request closed without merging**
