### PR TITLE
Feature: Support `restore` subcommand in `dolt_backup()` 

### PR DESCRIPTION
**Pull request by fulghum**
The `dolt_backup()` stored procedure now supports the `restore` subcommand. Customers can use this support to create a new database from an existing backup, or to sync an existing database from a backup. Note that the `restore` subcommand currently requires root/superuser access to execute, since it can change database state (particular when the `--force` argument is used). 

Example usage to create a database named `db1` from a backup on disk:
```sql
call dolt_backup('restore', 'file:///opt/local/dolt-backups/db1', 'db1');
```

Related to https://github.com/dolthub/dolt/issues/7993

Fixes https://github.com/dolthub/dolt/issues/6074

### CODE REVIEW

**Comment by timsehn** [comment]
Will this also make `dolt backup restore` go through the SQL insterface if a running server is detected? Or is that for later?

**Comment by timsehn** [comment]
> Will this also make `dolt backup restore` go through the SQL interface if a running server is detected? Or is that for later?

Looks like no: https://github.com/dolthub/dolt/issues/7628

**Comment by fulghum** [comment]
> > Will this also make `dolt backup restore` go through the SQL interface if a running server is detected? Or is that for later?
> 
> Looks like no: #7628

Correct – #7628 tracks the next step to make the CLI command use the stored procedure. I figured we should get the stored procedure support out first so the customer had a non-dolt_clone approach for backups from within SQL, then follow up for the CLI conversion. Happy to look at that next.

**Comment by timsehn** [comment]
I think this user still would have hit the issue and gotten confused if it did not go through the SQL interface. Probably worth taking the few hours and cleaning it up tomorrow.

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>057e3c8</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>057e3c8</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by jycor — APPROVED** [review]
LGTM!

Maybe add some tests with backing up branches and working/staged changes.
These all seem to work as expected when testing locally.

**Comment by fulghum** [comment]
> LGTM!
> 
> Maybe add some tests with backing up branches and working/staged changes. These all seem to work as expected when testing locally.

Thanks James! Good suggestion on more tests. I've got some more to add tomorrow (forwarding `dolt backup` to the stored procedure), so I'll take a look at extending the tests as part of that, too.

**Comment by coffeegoddd** [comment]
@fulghum __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7f29618</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7f29618</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
