### PR TITLE
`SELECT ... INTO OUTFILE ...` tests

### PR DESCRIPTION
**Pull request by jycor**
This PR adds BATS tests for a `SELECT ... INTO OUTFILE ...` feature we're adding.

Companion pr: https://github.com/dolthub/go-mysql-server/pull/2317

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999562</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0b0009c</TD>
<TD>not ok</TD>
<TD>26</TD>
</TR>
<TR><TD>0b0009c</TD>
<TD>ok</TD>
<TD>5937431</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0b0009c</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999562</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999562</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>285f77e</TD>
<TD>not ok</TD>
<TD>26</TD>
</TR>
<TR><TD>285f77e</TD>
<TD>ok</TD>
<TD>5937431</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>285f77e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999562</TD>
</TR>
</table>

**Review by fulghum — APPROVED** [review]
Looks good, although we should add the new `TestSelectIntoFile` function into `dolt_engine_test.go`, too.

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999562</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>fe5547d</TD>
<TD>not ok</TD>
<TD>26</TD>
</TR>
<TR><TD>fe5547d</TD>
<TD>ok</TD>
<TD>5937431</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>fe5547d</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999562</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999562 to 99.999562</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>476c04e</TD>
<TD>not ok</TD>
<TD>26</TD>
</TR>
<TR><TD>476c04e</TD>
<TD>ok</TD>
<TD>5937431</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>476c04e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999562</TD>
</TR>
</table>

**Pull request merged**
