### PR TITLE
adding `--name-only` option for `dolt diff`

### PR DESCRIPTION
**Pull request by jycor**
This PR adds support for `--name-only` option for `dolt diff`, which just prints the tables that have changed between the two commits. This mirrors `git diff --name-only`.

fixes: https://github.com/dolthub/dolt/issues/7797

### CODE REVIEW

**Comment by timsehn** [comment]
Should this be `--name-only` to match Git? Seems better but maybe a vote in #dolt-internal?

**Comment by fulghum** [comment]
> Should this be `--name-only` to match Git? Seems better but maybe a vote in #dolt-internal?

Good question; I was wondering the same. My vote is to match git here, too.

**Review by fulghum — APPROVED** [review]
Code changes look good. My only comment is that it seems worth matching Git with `--name-only` here instead of changing it to `--table-only`. Let me know if you think there's a compelling reason not to match Git though.

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4a76f29</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4a76f29</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>348fdf5</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>348fdf5</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
