### PR TITLE
[no-release-notes] bump for time bytes proto

### PR DESCRIPTION
**Pull request by max-hoffman**
time SQL avoids string alloc and fmt.Sprintf

GMS: https://github.com/dolthub/go-mysql-server/pull/2782

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 59.99            | 58.92          | -1.78          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 0bd3f0668795df7f6a4ca06d09fb8144f89190cd | 40.69    | dolt           | f3d1a64b6c751ab29e076b770fd2e12ab937f520 | 40.2   | -1.2           |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 58.92          | -3.54          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 77c3bf6b0ded9f66e3d306367e21eefe85a0bff1 | 39.81    | dolt           | fb3e20e70c6e9f860f37c0aee619f1be63772f23 | 40.4   | 1.48           |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.62         | 0.62       | 0.0            |
| groupby_scan         | 16.41        | 16.71      | 1.83           |
| index_join           | 2.26         | 2.3        | 1.77           |
| index_join_scan      | 1.47         | 1.47       | 0.0            |
| index_scan           | 55.82        | 52.89      | -5.25          |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.47         | 5.47       | 0.0            |
| select_random_points | 0.65         | 0.65       | 0.0            |
| select_random_ranges | 0.65         | 0.65       | 0.0            |
| table_scan           | 55.82        | 52.89      | -5.25          |
| types_table_scan     | 147.61       | 142.39     | -3.54          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.21         | 6.21       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.87        | 11.65      | -1.85          |
| oltp_update_index     | 3.13         | 3.13       | 0.0            |
| oltp_update_non_index | 3.07         | 3.07       | 0.0            |
| oltp_write_only       | 6.21         | 6.21       | 0.0            |
| types_delete_insert   | 6.55         | 6.55       | 0.0            |

**Pull request closed without merging**
