### PR TITLE
Comparison literal expansion bump

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 96.866116</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>ea215c0</TD>
<TD>not ok</TD>
<TD>186073</TD>
</TR>
<TR><TD>ea215c0</TD>
<TD>ok</TD>
<TD>5751384</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>ea215c0</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>96.866116</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 99.33             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 212313284c6ed1949986b2b59367ca1af13dc76f | 22.47 | tpcc-scale-factor-1 | dolt        | ea215c0bc2d3b6a61ea6b854c2b453b2f267b0eb | 22.47 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.02                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.09                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.49                | 0.5               | 0         |
| oltp_read_only       | 8.13                | 8.28              | 0         |
| select_random_points | 0.78                | 0.8               | 0         |
| select_random_ranges | 0.94                | 0.95              | 0         |
| table_scan           | 52.89               | 54.83             | 0         |
| types_table_scan     | 132.49              | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.79                | 6.79              | 0         |
| oltp_insert           | 3.36                | 3.36              | 0         |
| oltp_read_write       | 15.83               | 16.12             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.36                | 3.43              | 0         |
| oltp_write_only       | 7.7                 | 7.84              | 0         |
| types_delete_insert   | 7.43                | 7.56              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 99.33               | 97.55             | 0         |


|      test_name      | server_name |              server_version              | tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | a85cb313e35f44d96f16a82c3c00c042f63d34a5 | 22.3 | tpcc-scale-factor-1 | dolt        | 934066c79e041ca372f9d2473fd078ba814a5e98 | 22.13 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.07                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.32             | 0         |
| index_join           | 5.18                | 5.09              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.5                 | 0.51              | 0         |
| oltp_read_only       | 8.43                | 8.43              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 134.9               | 137.35            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.91              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.12               | 16.12             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.98              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>8303534</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>8303534</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request closed without merging**
