### PR TITLE
[no-release-notes] bump for deleting indexed varchar filters

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3070592</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3070592</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 62.19            | 59.99          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 594fd2d2d772b9b1eab40e0584ff3c3033a96670 | 39.29 | tpcc-scale-factor-1 | dolt        | 307059240b6fdec4daf28fde4e63e3f0d75486ac | 39.87 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.01               | 17.01             | 0         |
| index_join           | 2.61                | 2.61              | 0         |
| index_join_scan      | 2.14                | 2.14              | 0         |
| index_scan           | 54.83               | 53.85             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.88              | 0         |
| select_random_points | 0.65                | 0.65              | 0         |
| select_random_ranges | 0.83                | 0.83              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 144.97              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.91              | 0         |
| oltp_read_write       | 11.87               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.91                | 2.91              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>6f9b1eb</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>6f9b1eb</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request closed without merging**
