### PR TITLE
Remove cry for help from `dolt sql --help`

### PR DESCRIPTION
**Pull request by nicktobey**
Fixes https://github.com/dolthub/dolt/issues/5916
Fixes https://github.com/dolthub/dolt/issues/5920

### CODE REVIEW

**Comment by timsehn** [comment]
lolz

**Review by timsehn — COMMENTED** [review]
Maybe a bats tests since we somehow f'ed it up once?

**Review by fulghum — APPROVED** [review]
Fix looks great. I liked Tim's suggestion for a quick BATS regression test, too.

**Comment by nicktobey** [comment]
> Maybe a bats tests since we somehow f'ed it up once?

Turns out we already had one, but it was broken.

In fixing it, I discovered https://github.com/dolthub/dolt/issues/5920.

Fixes https://github.com/dolthub/dolt/issues/5920

**Review by timsehn — APPROVED** [review]
Clever. I just reviewed the bats test but it now looks thorough.

**Pull request merged**
