### PR TITLE
[no-release-notes] bump for stats perf

### PR DESCRIPTION
**Pull request by max-hoffman**
re: https://github.com/dolthub/go-mysql-server/pull/2558

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>79f94f0</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>79f94f0</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 71.83            | 73.13          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | b4dc47360dc0d5235634c3e5e219110d5d1a1ddf | 32.98 | tpcc-scale-factor-1 | dolt        | 79f94f06bcba9d7809b0063d34db65ab3b6b98d2 | 32.52 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.81                | 2.81              | 0         |
| groupby_scan         | 17.01               | 16.71             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 3.25                | 2.52              | 1         |
| index_scan           | 53.85               | 52.89             | 0         |
| oltp_point_select    | 0.46                | 0.44              | 0         |
| oltp_read_only       | 7.56                | 7.43              | 0         |
| select_random_points | 0.75                | 0.74              | 0         |
| select_random_ranges | 0.92                | 0.9               | 0         |
| table_scan           | 55.82               | 54.83             | 0         |
| types_table_scan     | 139.85              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 5.99              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 13.95               | 13.7              | 0         |
| oltp_update_index     | 3.07                | 3.07              | 0         |
| oltp_update_non_index | 3.02                | 3.02              | 0         |
| oltp_write_only       | 6.43                | 6.32              | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 74.46            | 75.82          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | b4dc47360dc0d5235634c3e5e219110d5d1a1ddf | 33.07 | tpcc-scale-factor-1 | dolt        | 79f94f06bcba9d7809b0063d34db65ab3b6b98d2 | 33.06 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.81                | 2.81              | 0         |
| groupby_scan         | 17.01               | 17.01             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 3.25                | 2.57              | 1         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.46                | 0.46              | 0         |
| oltp_read_only       | 7.56                | 7.56              | 0         |
| select_random_points | 0.75                | 0.75              | 0         |
| select_random_ranges | 0.9                 | 0.9               | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 139.85              | 139.85            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 5.99              | 0         |
| oltp_insert           | 2.97                | 3.02              | 0         |
| oltp_read_write       | 13.7                | 13.95             | 0         |
| oltp_update_index     | 3.07                | 3.07              | 0         |
| oltp_update_non_index | 3.02                | 3.02              | 0         |
| oltp_write_only       | 6.32                | 6.43              | 0         |
| types_delete_insert   | 6.55                | 6.55              | 0         |

**Pull request closed without merging**
