### PR TITLE
[no-release-notes] bump for binder arena

### PR DESCRIPTION
**Pull request by max-hoffman**
todo: won't pass tests yet

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0586f29</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0586f29</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 81.48            | 80.03          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 49045eb8f791b695326596cab729ddb5d26ba612 | 25.98 | tpcc-scale-factor-1 | dolt        | 0586f292bfe4e6533d844d1da1fa584b937a586a | 26.1 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.91              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 5.18                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.18              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.49                | 0.5               | 0         |
| oltp_read_only       | 7.98                | 8.13              | 0         |
| select_random_points | 0.78                | 0.8               | 0         |
| select_random_ranges | 0.95                | 0.97              | 0         |
| table_scan           | 52.89               | 53.85             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 2.97                | 3.02              | 0         |
| oltp_read_write       | 14.46               | 14.73             | 0         |
| oltp_update_index     | 3.13                | 3.13              | 0         |
| oltp_update_non_index | 3.02                | 3.07              | 0         |
| oltp_write_only       | 6.43                | 6.55              | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 81.48            | 81.48          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | a05f499eee713ded8b3b65ac05a01e9e5718054f | 26.04 | tpcc-scale-factor-1 | dolt        | 0586f292bfe4e6533d844d1da1fa584b937a586a | 25.9 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.91              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.18              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.5                 | 0.5               | 0         |
| oltp_read_only       | 8.13                | 8.13              | 0         |
| select_random_points | 0.8                 | 0.8               | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 53.85               | 53.85             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.02              | 0         |
| oltp_read_write       | 14.73               | 14.73             | 0         |
| oltp_update_index     | 3.19                | 3.13              | 0         |
| oltp_update_non_index | 3.13                | 3.07              | 0         |
| oltp_write_only       | 6.55                | 6.55              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Pull request closed without merging**
