### PR TITLE
feat: adding zsh plugin

### PR DESCRIPTION
**Pull request by iloveitaly**
This isn't perfect, but it's a starting point. What would be better:

* Create a separate repo for just this script (`dolthub/zsh`) for easier installation
* Change gen-zsh to output the script to stdout like `gh`, `op`, and other popular tools

You can use this via a `for` loop in zinit like:

```
zinit wait lucid for \
  'https://github.com/iloveitaly/dolt/blob/zsh-plugin/dolt.plugin.zsh'
```

### CODE REVIEW

**Comment by timsehn** [comment]
We have one of these.

https://www.dolthub.com/blog/2021-11-15-zsh-completions-with-subcommands/

**Comment by timsehn** [comment]
It looks like there is a hidden command

dolt gen-zsh

**Comment by timsehn** [comment]
I see. You know about that :-) This is a shell script to make it even easier :-)

**Comment by timsehn** [comment]
@zachmu wrote the `gen-zsh` command. He should discuss this solution with you.

**Review by zachmu — COMMENTED** [review]
Thanks for the contribution!

I wasn't aware that outputting completion scripts to stdout was more common. Would it be better to change the gen-zsh command to do that?

**Comment by iloveitaly** [comment]
@zachmu I think so! Most popular cli tools do that (at least, gh cli and 1password)

**Comment by zachmu** [comment]
I made that change here:

https://github.com/dolthub/dolt/pull/6492

Want to add to that PR so your plugin works correctly? Your zsh skills are beyond mine :)

**Comment by zachmu** [comment]
I went ahead and merged that in, so you can simplify your zsh plugin to read from STDOUT at your convenience.

**Comment by zachmu** [comment]
It looks like this PR is now merged because I merged its commit as part of my PR, so feel free to open another one to get rid of the `--file` flag in the zsh plugin.

**Pull request merged**
