### PR TITLE
[auto-bump] [no-release-notes] dependency by max-hoffman

### PR DESCRIPTION
**Pull request by coffeegoddd**
:coffee: *An Automated Dependency Version Bump PR* :crown:

### Initial Changes

The initial changes contained in this PR were produced by \`go get\`ing the dependency.

\`\`\`
\$ cd ./go
\$ go get github.com/dolthub/<dependency>/go@<commit>
\`\`\`

### Before Merging

This PR must have passing CI and a review before merging.

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 134.9               | 82.96             | 1         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 92beb505a90a943bf8e5c70935f9875edc5e37c3 | 14.45 | tpcc-scale-factor-1 | dolt        | a64443756427878ad3be0239b630fe61985143a3 | 0.32 | 1         |

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999848 to 99.999933</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a644437</TD>
<TD>not ok</TD>
<TD>4</TD>
</TR>
<TR><TD>a644437</TD>
<TD>ok</TD>
<TD>5937453</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a644437</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999933</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.02                | 2.97              | 0         |
| groupby_scan         | 18.28               | 18.61             | 0         |
| index_join           | 5.28                | 5.18              | 0         |
| index_join_scan      | 2.26                | 2.3               | 0         |
| index_scan           | 64.47               | 64.47             | 0         |
| oltp_point_select    | 0.48                | 0.47              | 0         |
| oltp_read_only       | 8.28                | 7.98              | 0         |
| select_random_points | 0.78                | 0.77              | 0         |
| select_random_ranges | 0.92                | 0.92              | 0         |
| table_scan           | 64.47               | 64.47             | 0         |
| types_table_scan     | 176.73              | 173.58            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 15.55               | 15.27             | 0         |
| oltp_update_index     | 3.13                | 3.07              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 7.56                | 7.43              | 0         |
| types_delete_insert   | 6.79                | 6.79              | 0         |

**Comment by coffeegoddd** [comment]
This PR has been superseded by https://github.com/dolthub/dolt/pull/7523

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999848 to 99.999933</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3c26993</TD>
<TD>not ok</TD>
<TD>4</TD>
</TR>
<TR><TD>3c26993</TD>
<TD>ok</TD>
<TD>5937453</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3c26993</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999933</TD>
</TR>
</table>

**Pull request closed without merging**
