### PR TITLE
bump

### PR DESCRIPTION
**Pull request by jycor**

### CODE REVIEW

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>bf02819</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>bf02819</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 59.99            | 58.92          | -1.78          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 486e50f4dc41af010f4c417cda38000129ae15de | 40.67    | dolt           | bf0281962a1c88977ae60077bdb702eef1edc54f | 40.97  | 0.74           |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.62         | 0.62       | 0.0            |
| groupby_scan         | 17.01        | 17.01      | 0.0            |
| index_join           | 2.35         | 2.35       | 0.0            |
| index_join_scan      | 1.86         | 1.86       | 0.0            |
| index_scan           | 55.82        | 55.82      | 0.0            |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.47         | 5.37       | -1.83          |
| select_random_points | 0.61         | 0.61       | 0.0            |
| select_random_ranges | 0.62         | 0.62       | 0.0            |
| table_scan           | 55.82        | 55.82      | 0.0            |
| types_table_scan     | 147.61       | 144.97     | -1.79          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 5.88         | 5.88       | 0.0            |
| oltp_insert           | 2.91         | 2.91       | 0.0            |
| oltp_read_write       | 11.24        | 11.45      | 1.87           |
| oltp_update_index     | 2.97         | 2.97       | 0.0            |
| oltp_update_non_index | 2.91         | 2.91       | 0.0            |
| oltp_write_only       | 5.99         | 5.99       | 0.0            |
| types_delete_insert   | 6.43         | 6.32       | -1.71          |

**Pull request closed without merging**
