### PR TITLE
[no-release-notes] Filtered reader optimization for `__DOLT_1__`

### PR DESCRIPTION
**Pull request by andrew-wm-arthur**
optimizations for various SQL access patterns:
1. use projection information during SQL row construction
2. reduce allocation sizes for `val.TupleBuilder`
3. use `prolly.Range` objects to filter index lookup rows on the Dolt side, and to remove filers in SQL plan

As a result of 3, query plans for the current and new formats are now equivalent.

depends on https://github.com/dolthub/go-mysql-server/pull/1098

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
#newbenchmark

**Comment by andrew-wm-arthur** [comment]
#newbenchmark

**Comment by andrew-wm-arthur** [comment]
#newbenchmark

**Review by zachmu — APPROVED** [review]
LGTM

**Pull request merged**
