### PR TITLE
[no-release-notes] follow up fixes to mcv calculation

### PR DESCRIPTION
**Pull request by max-hoffman**
Previous bug was only saving last MCV. Fix and add better testing.

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Review by nicktobey — APPROVED** [review]

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>53d0215</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>53d0215</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 73.13            | 74.46          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 12f2a8d540a17172f3c8c8f0d88e3e82cb7b7aec | 33.18 | tpcc-scale-factor-1 | dolt        | 53d0215ccfa1c407c780908cbd0309d957de9648 | 32.53 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 2.91              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.28                | 5.28              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.52                | 0.52              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.83              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 15.0                | 15.27             | 0         |
| oltp_update_index     | 3.13                | 3.19              | 0         |
| oltp_update_non_index | 3.07                | 3.07              | 0         |
| oltp_write_only       | 6.55                | 6.67              | 0         |
| types_delete_insert   | 6.79                | 6.91              | 0         |

**Pull request merged**
