### PR TITLE
[no-release-notes] bump for self-join stats perf

### PR DESCRIPTION
**Pull request by max-hoffman**
re: https://github.com/dolthub/go-mysql-server/pull/2606

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>05489e3</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>05489e3</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 71.83            | 75.82          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | dda3c30376b55d87d2e0fbce82ebd6560d58c1f2 | 34.23 | tpcc-scale-factor-1 | dolt        | 05489e3204111ac890b923439f205bd60fffcf4b | 34.3 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 2.81                | 2.81              | 0         |
| index_join_scan      | 2.57                | 2.22              | 1         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.46                | 0.46              | 0         |
| oltp_read_only       | 7.56                | 7.7               | 0         |
| select_random_points | 0.77                | 0.77              | 0         |
| select_random_ranges | 0.9                 | 0.9               | 0         |
| table_scan           | 55.82               | 55.82             | 0         |
| types_table_scan     | 142.39              | 144.97            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.09                | 6.09              | 0         |
| oltp_insert           | 3.02                | 3.07              | 0         |
| oltp_read_write       | 13.95               | 13.95             | 0         |
| oltp_update_index     | 3.07                | 3.13              | 0         |
| oltp_update_non_index | 3.02                | 3.02              | 0         |
| oltp_write_only       | 6.32                | 6.32              | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Pull request closed without merging**
