### PR TITLE
[dsess] Cache checks lookup for TPC-C update

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>5d23e91</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>5d23e91</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.63               | 17.63             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 53.85               | 53.85             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 7.04                | 6.91              | 0         |

**Review by zachmu — APPROVED** [review]
LGTM

**Pull request merged**
