### PR TITLE
Support VARCHAR(MAX)

### PR DESCRIPTION
**Pull request by rafimuhammad01**
Parse MAX in varchar(MAX) to its real value which is 16383. 

related issue #2261

### CODE REVIEW

**Review by timsehn — COMMENTED** [review]
Thank you so much for the contribution. I actually think this needs to go in [go-mysql-server](https://github.com/dolthub/go-mysql-server) as it is functionality we would want to work across all integrators.

I'm not exactly certain where this code lives there but @zachmu or @fulghum can point you there.

Here's a guide for how to contribute/test go-mysql-server:

https://docs.dolthub.com/guides/contributing/go-mysql-server

**Comment by fulghum** [comment]
Hey @rafimuhammad01, thank you for taking the time to send us this contribution! This will be a great feature to support. 🙏 
 I think the general approach of looking for `MAX` and replacing it with the max value is good, and I agree with Tim that if we push this lower, into go-mysql-server, then it'll work much more broadly. 

Take a look at this method in go-mysql-server that creates a string type: 
https://github.com/dolthub/go-mysql-server/blob/main/sql/stringtype.go#L97

That function takes in an integer length for the new string type, so we'd want to transform `MAX` right before we get into that code. Take a look at where that function is getting called and see if you can find where the parser calls it as it parses a column definition. Let us know if you get stuck and we're happy to dig in deeper and find a more exact spot for this code.

**Comment by rafimuhammad01** [comment]
Hi @timsehn @fulghum thanks for the feedback.

I agree that it is better to implementing on go-mysql-server. Will check the code and submit my PR soon. Cheers! 🍻

**Comment by timsehn** [comment]
Cool. I'll close this one :-)

**Pull request closed without merging**
