### PR TITLE
proj bump

### PR DESCRIPTION
**Pull request by jycor**

### CODE REVIEW

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>534d455</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>534d455</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 66.84            | 68.05          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 39.17 | tpcc-scale-factor-1 | dolt        | 534d4554fce130e998d6f75b95db9af8689e5be8 | 38.75 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.67              | 0         |
| groupby_scan         | 16.41               | 16.41             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.07                | 2.0               | 0         |
| index_scan           | 55.82               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.77              | 0         |
| select_random_points | 0.69                | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 56.84               | 56.84             | 0         |
| types_table_scan     | 147.61              | 147.61            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.88                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 12.08               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by jycor** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 63.32            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 8b0d9a1765b398cb8dc3d9b7e6ff3ffc65934127 | 38.88 | tpcc-scale-factor-1 | dolt        | 534d4554fce130e998d6f75b95db9af8689e5be8 | 39.62 | 0         |

**Comment by coffeegoddd** [comment]
@jycor __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 0.67                | 0.67              | 0         |
| groupby_scan         | 16.41               | 16.41             | 0         |
| index_join           | 2.57                | 2.48              | 0         |
| index_join_scan      | 2.07                | 2.0               | 0         |
| index_scan           | 56.84               | 55.82             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.77              | 0         |
| select_random_points | 0.7                 | 0.65              | 0         |
| select_random_ranges | 0.7                 | 0.7               | 0         |
| table_scan           | 56.84               | 56.84             | 0         |
| types_table_scan     | 147.61              | 147.61            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Pull request closed without merging**
