### PR TITLE
[writer] skip more deserialization steps in getTableWriter

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>6458a51</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>6458a51</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 84.47            | 82.96          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | c2d837e9d5b70ebf96a08444fe4bd45d395f52b7 | 24.63 | tpcc-scale-factor-1 | dolt        | 6458a51793a653ed5c3818fb368ec5ddaa05cac2 | 25.61 | 0         |

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>d79b207</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>d79b207</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.91                | 3.07              | 0         |
| groupby_scan         | 17.01               | 17.32             | 0         |
| index_join           | 5.28                | 5.18              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.5                 | 0.51              | 0         |
| oltp_read_only       | 8.13                | 8.28              | 0         |
| select_random_points | 0.8                 | 0.81              | 0         |
| select_random_ranges | 0.95                | 0.97              | 0         |
| table_scan           | 53.85               | 54.83             | 0         |
| types_table_scan     | 132.49              | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.02                | 3.07              | 0         |
| oltp_read_write       | 14.73               | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.55                | 6.67              | 0         |
| types_delete_insert   | 6.91                | 6.91              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.07              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.18                | 5.18              | 0         |
| index_join_scan      | 2.22                | 2.22              | 0         |
| index_scan           | 52.89               | 52.89             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.28                | 8.28              | 0         |
| select_random_points | 0.81                | 0.81              | 0         |
| select_random_ranges | 0.97                | 0.97              | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 134.9               | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.21                | 6.21              | 0         |
| oltp_insert           | 3.07                | 3.07              | 0         |
| oltp_read_write       | 15.0                | 15.0              | 0         |
| oltp_update_index     | 3.19                | 3.19              | 0         |
| oltp_update_non_index | 3.13                | 3.13              | 0         |
| oltp_write_only       | 6.67                | 6.67              | 0         |
| types_delete_insert   | 6.91                | 6.91              | 0         |

**Review by zachmu — APPROVED** [review]
LGTM

**Pull request merged**
