### PR TITLE
[no-release-notes] Fix issue where `dolt diff` fails to display changes to database schema if database name begins or ends with A, B, D, E, S, T,  or _ (case sensitive)

### PR DESCRIPTION
**Pull request by nicktobey**
This was discovered by running [`golangci-lint`](https://golangci-lint.run/), which returned the following check failure:

```
cmd/dolt/commands/diff.go:913:38: SA1024: cutset contains duplicate characters (staticcheck)
        tableName = strings.Trim(tableName, diff.DBPrefix)
```

Reproduction example:

```
> # correct behavior
> mkdir doltRepo
> cd doltRepo
> dolt init
> dolt sql -q "ALTER DATABASE doltRepo COLLATE latin1_swedish_ci;"
> dolt diff
diff --dolt a/__DATABASE__doltRepo b/__DATABASE__doltRepo
--- a/__DATABASE__doltRepo
+++ b/__DATABASE__doltRepo
+CREATE DATABASE `doltRepo` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;

> # incorrect behavior
> cd ..
> mv doltRepo DoltRepo
> cd DoltRepo
> dolt diff
diff --dolt a/__DATABASE__DoltRepo b/__DATABASE__DoltRepo
--- a/__DATABASE__DoltRepo
+++ b/__DATABASE__DoltRepo
Primary key sets differ between revisions for table '__DATABASE__DoltRepo', skipping data diff
```

The culprit is this line in `diff.go`:

```go
tableName = strings.Trim(tableName, diff.DBPrefix)
```

`strings.Trim` does not remove a prefix. Rather, it removes every character from the start and end of the input string that matches a character in the second parameter. In this case, the second parameter is the constant string `__DATABASE__`, leading to all of these characters getting stripped from the table name.

We actually want to call `strings.TrimPrefix` instead.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4c330aa</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4c330aa</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by jycor — APPROVED** [review]
LGTM

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e658448</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e658448</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>fde045c</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>fde045c</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>395d903</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>395d903</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
