### PR TITLE
Added a `--branch` parameter to Dolt global arguments on the command line.

### PR DESCRIPTION
**Pull request by Nithinps021**
Screenshot 2023-08-15 at 12 05 23 PM

### CODE REVIEW

**Comment by timsehn** [comment]
Thanks for the contribution @macneale4 will look at this since he is the master of global args.

**Comment by timsehn** [comment]
Addresses #6273

**Comment by macneale4** [comment]
Hi @Nithinps021 - Thanks for the PR! The addition of the --branch flag is something we considered, but hadn't pulled the trigger yet because we do have support for it in the specification of the DB name. If you want start your session on the `dev` branch, you would specify `--use-db=database_name/dev`

If you would like to continue and add the flag, I suggest you leverage that code path which is earlier in processing. Essentially adding it to the `useDB` variable here: https://github.com/dolthub/dolt/blob/559cbcbefc261e0f9119c28bb4893d4dcaaf1135/go/cmd/dolt/dolt.go#L611

The benefit of doing it this way is that all global argument enabled commands can take advantage of it.

Thanks again!

**Comment by timsehn** [comment]
Closing this pending the rework Neil suggested.

**Pull request closed without merging**
