### PR TITLE
go/store/nbs: Make the panic in the finalizer for an unclosed table file index always on.

### PR DESCRIPTION
**Pull request by reltuk**
Add a flag to make it not take the stack trace at the time of index creation.
Disable stack trace taking by default.

Make all unit tests pass the sanity checking.

### CODE REVIEW

**Review by andy-wm-arthur — COMMENTED** [review]
I'm uncertain if we want to capture the stack trace by default. I think I prefer not to do this for Dolt releases in particular, and to only leave it on for dev builds and services

**Comment by reltuk** [comment]
> I'm uncertain if we want to capture the stack trace by default. I think I prefer not to do this for Dolt releases in particular, and to only leave it on for dev builds and services

Yeah, the way it is set up here, it is enabled by default in services and unit tests. Every dolt release has it off. Technically remotesrv in this PR also has it on…

**Comment by timsehn** [comment]
We ever gonna merge this?

**Comment by reltuk** [comment]
@timsehn I'll sync up with Andy about whether we should and whether the defaults are currently right.

**Review by andy-wm-arthur — APPROVED** [review]
LGTM!

**Pull request merged**
