### PR TITLE
Use `LazyJSONDocument` when reading from a JSON column.

### PR DESCRIPTION
**Pull request by nicktobey**
This is the Dolt side of https://github.com/dolthub/dolt/issues/7749

The GMS PR is https://github.com/dolthub/go-mysql-server/pull/2470

`LazyJSONDocument` is an alternate implementation of `sql.JSONWrapper` that takes a string of serialized JSON and defers deserialization until it's actually required.

This is useful because in the most common use case (selecting a JSON column), deserialization is *never* required.

In an extreme example, I created a table with 8000 rows, with each row containing a 80KB JSON document.

`dolt sql -q "SELECT * FROM test_table"` ran in 47 seconds using `JSONDocument`, and 28 seconds using `LazyJSONDocument`, nearly half the time.

Even in cases where we do need to deserialize the JSON in order to filter on it, we can avoid reserializing it afterward, which is still a performance win.

Of note: In some cases we use a special serializer (defined in `json_encode.go::marshalToMySqlString`) in order to produce a string that is, according to the docstring "compatible with MySQL's JSON output, including spaces."

This currently gets used
- In Query Diff
- When hashing values for fulltext tables
- When casting JSON columns to a text type
- When writing values along the wire

The last one is the most worrying, because it means that we can't avoid the serialization round-trip if we're connecting to a dolt server remotely. I discussed with Max whether or not we consider it a requirement to match MySQL's wire responses exactly for JSON, and agreed that we could probably relax that requirement. Casting a document to a text type will still result in the same output as MySQL.

### CODE REVIEW

**Comment by nicktobey** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 94.1                | 89.16             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | a516aa4ef736171c1796a4bcbcf26578072f8ffd | 14.71 | tpcc-scale-factor-1 | dolt        | 692c76f362efe165c9703e3b6fb7e77426837096 | 7.12 | 1         |

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.07                | 3.02              | 0         |
| groupby_scan         | 17.63               | 17.32             | 0         |
| index_join           | 5.18                | 5.28              | 0         |
| index_join_scan      | 2.26                | 2.26              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.51                | 0.51              | 0         |
| oltp_read_only       | 8.58                | 8.58              | 0         |
| select_random_points | 0.83                | 0.83              | 0         |
| select_random_ranges | 0.99                | 0.99              | 0         |
| table_scan           | 53.85               | 54.83             | 0         |
| types_table_scan     | 161.51              | 137.35            | 1         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.91              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.41               | 16.41             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.84                | 7.98              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>2c69904</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>2c69904</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0b3caef</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0b3caef</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>48ef9e8</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>48ef9e8</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by nicktobey** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9b105e7</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9b105e7</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>78ec207</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>78ec207</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 95.81             | 0         |


|      test_name      | server_name |              server_version              | tps  |      test_name      | server_name |              server_version              | tps  | is_faster |
|---------------------|-------------|------------------------------------------|------|---------------------|-------------|------------------------------------------|------|-----------|
| tpcc-scale-factor-1 | dolt        | 4249386521febfef9b38935ef73ed044483cda64 | 2.16 | tpcc-scale-factor-1 | dolt        | 78ec207a46506e631556bb6d7efaf580c405facf | 0.09 | 1         |

**Comment by coffeegoddd** [comment]
@nicktobey __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 3.02                | 3.02              | 0         |
| groupby_scan         | 17.63               | 17.01             | 0         |
| index_join           | 5.18                | 5.09              | 0         |
| index_join_scan      | 2.22                | 2.18              | 0         |
| index_scan           | 52.89               | 51.94             | 0         |
| oltp_point_select    | 0.51                | 0.5               | 0         |
| oltp_read_only       | 8.43                | 8.13              | 0         |
| select_random_points | 0.8                 | 0.78              | 0         |
| select_random_ranges | 0.95                | 0.95              | 0         |
| table_scan           | 53.85               | 51.94             | 0         |
| types_table_scan     | 155.8               | 132.49            | 1         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.91                | 6.79              | 0         |
| oltp_insert           | 3.43                | 3.43              | 0         |
| oltp_read_write       | 16.12               | 15.83             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.98                | 7.84              | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Pull request merged**
