### PR TITLE
[dsess] reuse db start state maps

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>045b9a6</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>045b9a6</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 97.55             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 4b7710fe33d6601704c88a09b2bc773bdbc7c31c | 22.93 | tpcc-scale-factor-1 | dolt        | 045b9a6d5acb23bf71c3cb38634dbadaac7ce0fa | 22.95 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 3.02              | 0         |
| groupby_scan         | 17.32               | 17.63             | 0         |
| index_join           | 5.0                 | 5.18              | 0         |
| index_join_scan      | 2.18                | 2.22              | 0         |
| index_scan           | 51.94               | 52.89             | 0         |
| oltp_point_select    | 0.49                | 0.51              | 0         |
| oltp_read_only       | 8.13                | 8.28              | 0         |
| select_random_points | 0.78                | 0.8               | 0         |
| select_random_ranges | 0.94                | 0.97              | 0         |
| table_scan           | 52.89               | 54.83             | 0         |
| types_table_scan     | 132.49              | 134.9             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.67                | 6.67              | 0         |
| oltp_insert           | 3.25                | 3.3               | 0         |
| oltp_read_write       | 15.55               | 15.83             | 0         |
| oltp_update_index     | 3.49                | 3.55              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.56                | 7.7               | 0         |
| types_delete_insert   | 7.56                | 7.56              | 0         |

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>2a1021c</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>2a1021c</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 97.55               | 97.55             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 4b7710fe33d6601704c88a09b2bc773bdbc7c31c | 23.22 | tpcc-scale-factor-1 | dolt        | 2a1021c8dadf78f2d2eeef2ed20fc9cbae9deabb | 22.67 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.97                | 2.97              | 0         |
| groupby_scan         | 17.32               | 17.32             | 0         |
| index_join           | 5.09                | 5.09              | 0         |
| index_join_scan      | 2.18                | 2.18              | 0         |
| index_scan           | 51.94               | 51.94             | 0         |
| oltp_point_select    | 0.49                | 0.49              | 0         |
| oltp_read_only       | 8.13                | 8.13              | 0         |
| select_random_points | 0.78                | 0.78              | 0         |
| select_random_ranges | 0.95                | 0.95              | 0         |
| table_scan           | 52.89               | 52.89             | 0         |
| types_table_scan     | 130.13              | 130.13            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 6.67                | 6.67              | 0         |
| oltp_insert           | 3.25                | 3.25              | 0         |
| oltp_read_write       | 15.55               | 15.55             | 0         |
| oltp_update_index     | 3.49                | 3.49              | 0         |
| oltp_update_non_index | 3.43                | 3.43              | 0         |
| oltp_write_only       | 7.43                | 7.56              | 0         |
| types_delete_insert   | 7.56                | 7.43              | 0         |

**Comment by max-hoffman** [comment]
closing, negligible perf effect

**Pull request closed without merging**
