### PR TITLE
/go/store/nbs: Optimize NBS rebase

### PR DESCRIPTION
**Pull request by andrew-wm-arthur**

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Comment by andrew-wm-arthur** [comment]
#benchmark

**Review by reltuk — APPROVED** [review]
LGTM!

**Pull request merged**
