### PR TITLE
Skip filterIter match check when a key range is contiguous

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 99.960017</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>8bd7d58</TD>
<TD>not ok</TD>
<TD>2374</TD>
</TR>
<TR><TD>8bd7d58</TD>
<TD>ok</TD>
<TD>5935083</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>8bd7d58</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.960017</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 61.08            | 62.19          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 2c1b0854ac925e9ebac3978219443de72e0803e4 | 39.36 | tpcc-scale-factor-1 | dolt        | 8bd7d5836f44609f42421427f78ebffa52152bba | 38.97 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 1.21                | 0.77              | 1         |
| groupby_scan         | 17.32               | 17.01             | 0         |
| index_join           | 2.71                | 2.66              | 0         |
| index_join_scan      | 2.14                | 2.03              | 0         |
| index_scan           | 53.85               | 53.85             | 0         |
| oltp_point_select    | 0.3                 | 0.3               | 0         |
| oltp_read_only       | 5.88                | 5.99              | 0         |
| select_random_points | 0.65                | 0.65              | 0         |
| select_random_ranges | 0.8                 | 0.8               | 0         |
| table_scan           | 54.83               | 54.83             | 0         |
| types_table_scan     | 142.39              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 3.02                | 3.02              | 0         |
| oltp_read_write       | 12.08               | 12.08             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.21                | 6.21              | 0         |
| types_delete_insert   | 6.43                | 6.55              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0f259d6</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0f259d6</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by max-hoffman** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 99.991949</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>928a7cf</TD>
<TD>not ok</TD>
<TD>478</TD>
</TR>
<TR><TD>928a7cf</TD>
<TD>ok</TD>
<TD>5936979</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>928a7cf</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.991949</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | is_faster |
|---------------------|------------------|----------------|-----------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 2c1b0854ac925e9ebac3978219443de72e0803e4 | 39.44 | tpcc-scale-factor-1 | dolt        | 928a7cf18347160158b8e6b222732e577c6d6930 | 39.42 | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 1.21                | 0.77              | 1         |
| groupby_scan         | 17.32               | 16.41             | 0         |
| index_join           | 2.61                | 2.61              | 0         |
| index_join_scan      | 2.14                | 2.14              | 0         |
| index_scan           | 54.83               | 54.83             | 0         |
| oltp_point_select    | 0.29                | 0.29              | 0         |
| oltp_read_only       | 5.88                | 5.88              | 0         |
| select_random_points | 0.65                | 0.65              | 0         |
| select_random_ranges | 0.8                 | 0.78              | 0         |
| table_scan           | 54.83               | 55.82             | 0         |
| types_table_scan     | 144.97              | 142.39            | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.99              | 0         |
| oltp_insert           | 2.97                | 2.97              | 0         |
| oltp_read_write       | 11.87               | 11.87             | 0         |
| oltp_update_index     | 3.02                | 3.02              | 0         |
| oltp_update_non_index | 2.97                | 2.97              | 0         |
| oltp_write_only       | 6.09                | 6.09              | 0         |
| types_delete_insert   | 6.43                | 6.43              | 0         |

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c8c3819</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c8c3819</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by zachmu — APPROVED** [review]
This seems fine, but would be good to have an engine test that exercises the specific edge case being targeted.

**Comment by max-hoffman** [comment]
> This seems fine, but would be good to have an engine test that exercises the specific edge case being targeted.

The process of implementing this PR broke suites I didn't even know existed. We test traditional indexes and ranges in a lot of ways. The one gap seemed to be NULL ranges, I added a test in GMS that is a canary for that pattern, but we could probably do better there https://github.com/dolthub/go-mysql-server/pull/2630

**Comment by coffeegoddd** [comment]
@max-hoffman __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>c9b1ae7</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>c9b1ae7</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Pull request merged**
