### PR TITLE
Experimental pgo file

### PR DESCRIPTION
**Pull request by zachmu**

### CODE REVIEW

**Comment by zachmu** [comment]
#benchmark

**Comment by coffeegoddd** [comment]
@zachmu __DOLT__
 |      test_name      | from_latency_median | to_latency_median | is_faster |
|---------------------|---------------------|-------------------|-----------|
| tpcc-scale-factor-1 | 164.45              | 155.8             | 0         |


|      test_name      | server_name |              server_version              |  tps  |      test_name      | server_name |              server_version              |  tps  | is_faster |
|---------------------|-------------|------------------------------------------|-------|---------------------|-------------|------------------------------------------|-------|-----------|
| tpcc-scale-factor-1 | dolt        | 6cf79315792af90d550b584a1d1945e69d804c39 | 23.37 | tpcc-scale-factor-1 | dolt        | 3b627a404296197e74901a16d4f71b4183c68e72 | 25.19 | 0         |

**Comment by coffeegoddd** [comment]
@zachmu __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>99.999074 to 99.999074</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3b627a4</TD>
<TD>not ok</TD>
<TD>55</TD>
</TR>
<TR><TD>3b627a4</TD>
<TD>ok</TD>
<TD>5937402</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3b627a4</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>99.999074</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@zachmu __DOLT__
 |      read_tests      | from_latency_median | to_latency_median | is_faster |
|----------------------|---------------------|-------------------|-----------|
| covering_index_scan  | 2.86                | 2.57              | 1         |
| groupby_scan         | 17.63               | 16.41             | 0         |
| index_join           | 5.18                | 4.91              | 0         |
| index_join_scan      | 2.18                | 2.14              | 0         |
| index_scan           | 63.32               | 57.87             | 0         |
| oltp_point_select    | 0.46                | 0.46              | 0         |
| oltp_read_only       | 8.13                | 7.84              | 0         |
| select_random_points | 0.75                | 0.75              | 0         |
| select_random_ranges | 0.9                 | 0.86              | 0         |
| table_scan           | 63.32               | 57.87             | 0         |
| types_table_scan     | 170.48              | 155.8             | 0         |


|      write_tests      | from_latency_median | to_latency_median | is_faster |
|-----------------------|---------------------|-------------------|-----------|
| oltp_delete_insert    | 5.99                | 5.88              | 0         |
| oltp_insert           | 2.97                | 2.91              | 0         |
| oltp_read_write       | 15.27               | 15.0              | 0         |
| oltp_update_index     | 3.13                | 3.07              | 0         |
| oltp_update_non_index | 3.07                | 3.02              | 0         |
| oltp_write_only       | 7.43                | 7.3               | 0         |
| types_delete_insert   | 6.67                | 6.67              | 0         |

**Comment by timsehn** [comment]
I think we close this correct?

**Comment by timsehn** [comment]
Should we close this now that we build with PGO?

**Pull request closed without merging**
